// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: shardsservice/shards.proto

package shardsservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhaseOneResponse_Status int32

const (
	PhaseOneResponse_CAN_COMMIT       PhaseOneResponse_Status = 0
	PhaseOneResponse_CANNOT_COMMITTED PhaseOneResponse_Status = 1
	PhaseOneResponse_COMMIT_DONE      PhaseOneResponse_Status = 2
)

// Enum value maps for PhaseOneResponse_Status.
var (
	PhaseOneResponse_Status_name = map[int32]string{
		0: "CAN_COMMIT",
		1: "CANNOT_COMMITTED",
		2: "COMMIT_DONE",
	}
	PhaseOneResponse_Status_value = map[string]int32{
		"CAN_COMMIT":       0,
		"CANNOT_COMMITTED": 1,
		"COMMIT_DONE":      2,
	}
)

func (x PhaseOneResponse_Status) Enum() *PhaseOneResponse_Status {
	p := new(PhaseOneResponse_Status)
	*p = x
	return p
}

func (x PhaseOneResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseOneResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_shardsservice_shards_proto_enumTypes[0].Descriptor()
}

func (PhaseOneResponse_Status) Type() protoreflect.EnumType {
	return &file_shardsservice_shards_proto_enumTypes[0]
}

func (x PhaseOneResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseOneResponse_Status.Descriptor instead.
func (PhaseOneResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{4, 0}
}

type PhaseTwoRequest_Instruction int32

const (
	PhaseTwoRequest_COMMIT PhaseTwoRequest_Instruction = 0
	PhaseTwoRequest_FORGET PhaseTwoRequest_Instruction = 1
)

// Enum value maps for PhaseTwoRequest_Instruction.
var (
	PhaseTwoRequest_Instruction_name = map[int32]string{
		0: "COMMIT",
		1: "FORGET",
	}
	PhaseTwoRequest_Instruction_value = map[string]int32{
		"COMMIT": 0,
		"FORGET": 1,
	}
)

func (x PhaseTwoRequest_Instruction) Enum() *PhaseTwoRequest_Instruction {
	p := new(PhaseTwoRequest_Instruction)
	*p = x
	return p
}

func (x PhaseTwoRequest_Instruction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseTwoRequest_Instruction) Descriptor() protoreflect.EnumDescriptor {
	return file_shardsservice_shards_proto_enumTypes[1].Descriptor()
}

func (PhaseTwoRequest_Instruction) Type() protoreflect.EnumType {
	return &file_shardsservice_shards_proto_enumTypes[1]
}

func (x PhaseTwoRequest_Instruction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseTwoRequest_Instruction.Descriptor instead.
func (PhaseTwoRequest_Instruction) EnumDescriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{6, 0}
}

type ShardsSetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstShardId uint32 `protobuf:"varint,1,opt,name=first_shard_id,json=firstShardId,proto3" json:"first_shard_id,omitempty"`
	LastShardId  uint32 `protobuf:"varint,2,opt,name=last_shard_id,json=lastShardId,proto3" json:"last_shard_id,omitempty"`
}

func (x *ShardsSetupRequest) Reset() {
	*x = ShardsSetupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardsSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardsSetupRequest) ProtoMessage() {}

func (x *ShardsSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardsSetupRequest.ProtoReflect.Descriptor instead.
func (*ShardsSetupRequest) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{0}
}

func (x *ShardsSetupRequest) GetFirstShardId() uint32 {
	if x != nil {
		return x.FirstShardId
	}
	return 0
}

func (x *ShardsSetupRequest) GetLastShardId() uint32 {
	if x != nil {
		return x.LastShardId
	}
	return 0
}

type SerialNumbers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerialNumbers [][]byte `protobuf:"bytes,1,rep,name=serial_numbers,json=serialNumbers,proto3" json:"serial_numbers,omitempty"`
}

func (x *SerialNumbers) Reset() {
	*x = SerialNumbers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialNumbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialNumbers) ProtoMessage() {}

func (x *SerialNumbers) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialNumbers.ProtoReflect.Descriptor instead.
func (*SerialNumbers) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{1}
}

func (x *SerialNumbers) GetSerialNumbers() [][]byte {
	if x != nil {
		return x.SerialNumbers
	}
	return nil
}

type PhaseOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum               uint64                    `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum                  uint64                    `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	ShardidToSerialNumbers map[uint32]*SerialNumbers `protobuf:"bytes,3,rep,name=shardid_to_serial_numbers,json=shardidToSerialNumbers,proto3" json:"shardid_to_serial_numbers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsCompleteTx           bool                      `protobuf:"varint,4,opt,name=is_complete_tx,json=isCompleteTx,proto3" json:"is_complete_tx,omitempty"`
}

func (x *PhaseOneRequest) Reset() {
	*x = PhaseOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseOneRequest) ProtoMessage() {}

func (x *PhaseOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseOneRequest.ProtoReflect.Descriptor instead.
func (*PhaseOneRequest) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{2}
}

func (x *PhaseOneRequest) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *PhaseOneRequest) GetTxNum() uint64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *PhaseOneRequest) GetShardidToSerialNumbers() map[uint32]*SerialNumbers {
	if x != nil {
		return x.ShardidToSerialNumbers
	}
	return nil
}

func (x *PhaseOneRequest) GetIsCompleteTx() bool {
	if x != nil {
		return x.IsCompleteTx
	}
	return false
}

type PhaseOneRequestBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*PhaseOneRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *PhaseOneRequestBatch) Reset() {
	*x = PhaseOneRequestBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseOneRequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseOneRequestBatch) ProtoMessage() {}

func (x *PhaseOneRequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseOneRequestBatch.ProtoReflect.Descriptor instead.
func (*PhaseOneRequestBatch) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{3}
}

func (x *PhaseOneRequestBatch) GetRequests() []*PhaseOneRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type PhaseOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum uint64                  `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum    uint64                  `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	Status   PhaseOneResponse_Status `protobuf:"varint,3,opt,name=status,proto3,enum=shardsservice.PhaseOneResponse_Status" json:"status,omitempty"`
}

func (x *PhaseOneResponse) Reset() {
	*x = PhaseOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseOneResponse) ProtoMessage() {}

func (x *PhaseOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseOneResponse.ProtoReflect.Descriptor instead.
func (*PhaseOneResponse) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{4}
}

func (x *PhaseOneResponse) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *PhaseOneResponse) GetTxNum() uint64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *PhaseOneResponse) GetStatus() PhaseOneResponse_Status {
	if x != nil {
		return x.Status
	}
	return PhaseOneResponse_CAN_COMMIT
}

type PhaseOneResponseBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*PhaseOneResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *PhaseOneResponseBatch) Reset() {
	*x = PhaseOneResponseBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseOneResponseBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseOneResponseBatch) ProtoMessage() {}

func (x *PhaseOneResponseBatch) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseOneResponseBatch.ProtoReflect.Descriptor instead.
func (*PhaseOneResponseBatch) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{5}
}

func (x *PhaseOneResponseBatch) GetResponses() []*PhaseOneResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type PhaseTwoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum    uint64                      `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum       uint64                      `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	Instruction PhaseTwoRequest_Instruction `protobuf:"varint,3,opt,name=instruction,proto3,enum=shardsservice.PhaseTwoRequest_Instruction" json:"instruction,omitempty"`
}

func (x *PhaseTwoRequest) Reset() {
	*x = PhaseTwoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseTwoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTwoRequest) ProtoMessage() {}

func (x *PhaseTwoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTwoRequest.ProtoReflect.Descriptor instead.
func (*PhaseTwoRequest) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{6}
}

func (x *PhaseTwoRequest) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *PhaseTwoRequest) GetTxNum() uint64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *PhaseTwoRequest) GetInstruction() PhaseTwoRequest_Instruction {
	if x != nil {
		return x.Instruction
	}
	return PhaseTwoRequest_COMMIT
}

type PhaseTwoRequestBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*PhaseTwoRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *PhaseTwoRequestBatch) Reset() {
	*x = PhaseTwoRequestBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseTwoRequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTwoRequestBatch) ProtoMessage() {}

func (x *PhaseTwoRequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTwoRequestBatch.ProtoReflect.Descriptor instead.
func (*PhaseTwoRequestBatch) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{7}
}

func (x *PhaseTwoRequestBatch) GetRequests() []*PhaseTwoRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardsservice_shards_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_shardsservice_shards_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_shardsservice_shards_proto_rawDescGZIP(), []int{8}
}

var File_shardsservice_shards_proto protoreflect.FileDescriptor

var file_shardsservice_shards_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x5e, 0x0a, 0x12, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x73, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x6c, 0x61, 0x73, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0d, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x22, 0xcb, 0x02, 0x0a, 0x0f, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x4e, 0x75, 0x6d, 0x12, 0x75, 0x0a, 0x19, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x69, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x16, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x69, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x78, 0x1a, 0x67, 0x0a, 0x1b, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x69, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x52, 0x0a, 0x14, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3a, 0x0a, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0xc7, 0x01, 0x0a, 0x10, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x4e, 0x75, 0x6d, 0x12, 0x3e,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x41, 0x4e, 0x5f,
	0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x41, 0x4e, 0x4e,
	0x4f, 0x54, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x22,
	0x56, 0x0a, 0x15, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3d, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x0f, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x4e, 0x75, 0x6d, 0x12,
	0x4c, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a,
	0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x4f, 0x52, 0x47,
	0x45, 0x54, 0x10, 0x01, 0x22, 0x52, 0x0a, 0x14, 0x50, 0x68, 0x61, 0x73, 0x65, 0x54, 0x77, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3a, 0x0a, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x32, 0xc6, 0x02, 0x0a, 0x06, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x12, 0x46, 0x0a, 0x0b,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x12, 0x21, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x73, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x64, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e,
	0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x23, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x24, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61,
	0x73, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x28, 0x01, 0x30, 0x01, 0x12, 0x52, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x54, 0x77, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x23, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x1a, 0x14, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x62, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2d, 0x72,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shardsservice_shards_proto_rawDescOnce sync.Once
	file_shardsservice_shards_proto_rawDescData = file_shardsservice_shards_proto_rawDesc
)

func file_shardsservice_shards_proto_rawDescGZIP() []byte {
	file_shardsservice_shards_proto_rawDescOnce.Do(func() {
		file_shardsservice_shards_proto_rawDescData = protoimpl.X.CompressGZIP(file_shardsservice_shards_proto_rawDescData)
	})
	return file_shardsservice_shards_proto_rawDescData
}

var file_shardsservice_shards_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shardsservice_shards_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shardsservice_shards_proto_goTypes = []interface{}{
	(PhaseOneResponse_Status)(0),     // 0: shardsservice.PhaseOneResponse.Status
	(PhaseTwoRequest_Instruction)(0), // 1: shardsservice.PhaseTwoRequest.Instruction
	(*ShardsSetupRequest)(nil),       // 2: shardsservice.ShardsSetupRequest
	(*SerialNumbers)(nil),            // 3: shardsservice.SerialNumbers
	(*PhaseOneRequest)(nil),          // 4: shardsservice.PhaseOneRequest
	(*PhaseOneRequestBatch)(nil),     // 5: shardsservice.PhaseOneRequestBatch
	(*PhaseOneResponse)(nil),         // 6: shardsservice.PhaseOneResponse
	(*PhaseOneResponseBatch)(nil),    // 7: shardsservice.PhaseOneResponseBatch
	(*PhaseTwoRequest)(nil),          // 8: shardsservice.PhaseTwoRequest
	(*PhaseTwoRequestBatch)(nil),     // 9: shardsservice.PhaseTwoRequestBatch
	(*Empty)(nil),                    // 10: shardsservice.Empty
	nil,                              // 11: shardsservice.PhaseOneRequest.ShardidToSerialNumbersEntry
}
var file_shardsservice_shards_proto_depIdxs = []int32{
	11, // 0: shardsservice.PhaseOneRequest.shardid_to_serial_numbers:type_name -> shardsservice.PhaseOneRequest.ShardidToSerialNumbersEntry
	4,  // 1: shardsservice.PhaseOneRequestBatch.requests:type_name -> shardsservice.PhaseOneRequest
	0,  // 2: shardsservice.PhaseOneResponse.status:type_name -> shardsservice.PhaseOneResponse.Status
	6,  // 3: shardsservice.PhaseOneResponseBatch.responses:type_name -> shardsservice.PhaseOneResponse
	1,  // 4: shardsservice.PhaseTwoRequest.instruction:type_name -> shardsservice.PhaseTwoRequest.Instruction
	8,  // 5: shardsservice.PhaseTwoRequestBatch.requests:type_name -> shardsservice.PhaseTwoRequest
	3,  // 6: shardsservice.PhaseOneRequest.ShardidToSerialNumbersEntry.value:type_name -> shardsservice.SerialNumbers
	2,  // 7: shardsservice.Shards.SetupShards:input_type -> shardsservice.ShardsSetupRequest
	10, // 8: shardsservice.Shards.DeleteShards:input_type -> shardsservice.Empty
	5,  // 9: shardsservice.Shards.StartPhaseOneStream:input_type -> shardsservice.PhaseOneRequestBatch
	9,  // 10: shardsservice.Shards.StartPhaseTwoStream:input_type -> shardsservice.PhaseTwoRequestBatch
	10, // 11: shardsservice.Shards.SetupShards:output_type -> shardsservice.Empty
	10, // 12: shardsservice.Shards.DeleteShards:output_type -> shardsservice.Empty
	7,  // 13: shardsservice.Shards.StartPhaseOneStream:output_type -> shardsservice.PhaseOneResponseBatch
	10, // 14: shardsservice.Shards.StartPhaseTwoStream:output_type -> shardsservice.Empty
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shardsservice_shards_proto_init() }
func file_shardsservice_shards_proto_init() {
	if File_shardsservice_shards_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shardsservice_shards_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardsSetupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialNumbers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseOneRequestBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseOneResponseBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseTwoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseTwoRequestBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardsservice_shards_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shardsservice_shards_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shardsservice_shards_proto_goTypes,
		DependencyIndexes: file_shardsservice_shards_proto_depIdxs,
		EnumInfos:         file_shardsservice_shards_proto_enumTypes,
		MessageInfos:      file_shardsservice_shards_proto_msgTypes,
	}.Build()
	File_shardsservice_shards_proto = out.File
	file_shardsservice_shards_proto_rawDesc = nil
	file_shardsservice_shards_proto_goTypes = nil
	file_shardsservice_shards_proto_depIdxs = nil
}
