//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: api/protoqueryservice/query.proto

package protoqueryservice

import (
	context "context"
	protoblocktx "github.ibm.com/decentralized-trust-research/scalable-committer/api/protoblocktx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QueryService_GetRows_FullMethodName              = "/protoqueryservice.QueryService/GetRows"
	QueryService_BeginView_FullMethodName            = "/protoqueryservice.QueryService/BeginView"
	QueryService_EndView_FullMethodName              = "/protoqueryservice.QueryService/EndView"
	QueryService_GetNamespacePolicies_FullMethodName = "/protoqueryservice.QueryService/GetNamespacePolicies"
	QueryService_GetConfigTransaction_FullMethodName = "/protoqueryservice.QueryService/GetConfigTransaction"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	GetRows(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Rows, error)
	BeginView(ctx context.Context, in *ViewParameters, opts ...grpc.CallOption) (*View, error)
	EndView(ctx context.Context, in *View, opts ...grpc.CallOption) (*View, error)
	GetNamespacePolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*protoblocktx.NamespacePolicies, error)
	GetConfigTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*protoblocktx.ConfigTransaction, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) GetRows(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Rows, error) {
	out := new(Rows)
	err := c.cc.Invoke(ctx, QueryService_GetRows_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) BeginView(ctx context.Context, in *ViewParameters, opts ...grpc.CallOption) (*View, error) {
	out := new(View)
	err := c.cc.Invoke(ctx, QueryService_BeginView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) EndView(ctx context.Context, in *View, opts ...grpc.CallOption) (*View, error) {
	out := new(View)
	err := c.cc.Invoke(ctx, QueryService_EndView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetNamespacePolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*protoblocktx.NamespacePolicies, error) {
	out := new(protoblocktx.NamespacePolicies)
	err := c.cc.Invoke(ctx, QueryService_GetNamespacePolicies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetConfigTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*protoblocktx.ConfigTransaction, error) {
	out := new(protoblocktx.ConfigTransaction)
	err := c.cc.Invoke(ctx, QueryService_GetConfigTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility
type QueryServiceServer interface {
	GetRows(context.Context, *Query) (*Rows, error)
	BeginView(context.Context, *ViewParameters) (*View, error)
	EndView(context.Context, *View) (*View, error)
	GetNamespacePolicies(context.Context, *Empty) (*protoblocktx.NamespacePolicies, error)
	GetConfigTransaction(context.Context, *Empty) (*protoblocktx.ConfigTransaction, error)
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (UnimplementedQueryServiceServer) GetRows(context.Context, *Query) (*Rows, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRows not implemented")
}
func (UnimplementedQueryServiceServer) BeginView(context.Context, *ViewParameters) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginView not implemented")
}
func (UnimplementedQueryServiceServer) EndView(context.Context, *View) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndView not implemented")
}
func (UnimplementedQueryServiceServer) GetNamespacePolicies(context.Context, *Empty) (*protoblocktx.NamespacePolicies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespacePolicies not implemented")
}
func (UnimplementedQueryServiceServer) GetConfigTransaction(context.Context, *Empty) (*protoblocktx.ConfigTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigTransaction not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_GetRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetRows(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_BeginView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).BeginView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_BeginView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).BeginView(ctx, req.(*ViewParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_EndView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(View)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).EndView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_EndView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).EndView(ctx, req.(*View))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetNamespacePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetNamespacePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetNamespacePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetNamespacePolicies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetConfigTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetConfigTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetConfigTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetConfigTransaction(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoqueryservice.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRows",
			Handler:    _QueryService_GetRows_Handler,
		},
		{
			MethodName: "BeginView",
			Handler:    _QueryService_BeginView_Handler,
		},
		{
			MethodName: "EndView",
			Handler:    _QueryService_EndView_Handler,
		},
		{
			MethodName: "GetNamespacePolicies",
			Handler:    _QueryService_GetNamespacePolicies_Handler,
		},
		{
			MethodName: "GetConfigTransaction",
			Handler:    _QueryService_GetConfigTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protoqueryservice/query.proto",
}
