/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package loadgen

import (
	"github.ibm.com/decentralized-trust-research/scalable-committer/loadgen/adapters"
	"github.ibm.com/decentralized-trust-research/scalable-committer/loadgen/metrics"
	"github.ibm.com/decentralized-trust-research/scalable-committer/loadgen/workload"
)

type (
	// ClientConfig is a struct that contains the configuration for the client.
	ClientConfig struct {
		Adapter adapters.AdapterConfig `mapstructure:",squash" yaml:",inline"`

		Monitoring metrics.Config `mapstructure:"monitoring" yaml:"monitoring"`

		LoadProfile *workload.Profile       `mapstructure:"load-profile" yaml:"load-profile"`
		Stream      *workload.StreamOptions `mapstructure:"stream" yaml:"stream"`
		Limit       *adapters.GenerateLimit `mapstructure:"limit" yaml:"limit"`

		// Generate If omitted, all phases will be generated by default.
		Generate adapters.Phases `mapstructure:"generate" yaml:"generate"`
	}
)
