/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package loadgen

import (
	"github.com/cockroachdb/errors"

	"github.com/hyperledger/fabric-x-committer/loadgen/adapters"
	"github.com/hyperledger/fabric-x-committer/loadgen/metrics"
	"github.com/hyperledger/fabric-x-committer/loadgen/workload"
	"github.com/hyperledger/fabric-x-committer/utils/connection"
)

type (
	// ClientConfig is a struct that contains the configuration for the client.
	ClientConfig struct {
		Monitoring metrics.Config `mapstructure:"monitoring" yaml:"monitoring"`

		Adapter     adapters.AdapterConfig  `mapstructure:",squash" yaml:",inline"`
		Stream      *workload.StreamOptions `mapstructure:"stream" yaml:"stream"`
		LoadProfile *workload.Profile       `mapstructure:"load-profile" yaml:"load-profile"`
		Limit       *adapters.GenerateLimit `mapstructure:"limit" yaml:"limit"`

		// QueryClient is the query-service connection used to fetch committed read versions for a
		// rate-controlled subset of each transaction's reads (load-profile.transaction.queries-rate)
		// before signing. One load-balanced connection is dialed per worker, round-robining across the
		// configured query-service endpoints. Required when queries-rate > 0.
		QueryClient *connection.MultiClientConfig `mapstructure:"query-client" yaml:"query-client"`

		// Generate If omitted, all phases will be generated by default.
		Generate adapters.Phases `mapstructure:"generate" yaml:"generate"`
	}
)

// Validate runs the cross-field configuration checks that struct `validate` tags can't express (a field
// compared to a sum of other fields). The config loader invokes it after struct-tag validation, so these
// rules are enforced at config load rather than at runtime.
func (c *ClientConfig) Validate() error {
	if c.LoadProfile == nil {
		return nil
	}
	if err := c.LoadProfile.Transaction.Validate(); err != nil {
		return err
	}
	if c.LoadProfile.Transaction.QueriesRate > 0 && c.QueryClient == nil {
		return errors.New("queries-rate > 0 requires query-client")
	}
	return nil
}
