#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

ops="${*:-db orderer committer loadgen}"

if [[ "$*" == *"--insecure"* ]]; then
  # Set TLS mode to none-tls.
  export SC_COORDINATOR_SERVER_TLS_MODE="none"
  export SC_COORDINATOR_VERIFIER_TLS_MODE="none"
  export SC_COORDINATOR_VALIDATOR_COMMITTER_TLS_MODE="none"
  export SC_QUERY_SERVER_TLS_MODE="none"
  export SC_SIDECAR_SERVER_TLS_MODE="none"
  export SC_SIDECAR_COMMITTER_TLS_MODE="none"
  export SC_SIDECAR_ORDERER_CONNECTION_TLS_MODE="none"
  export SC_VC_SERVER_TLS_MODE="none"
  export SC_VERIFIER_SERVER_TLS_MODE="none"
  export SC_ORDERER_SERVER_TLS_MODE="none"
  export SC_LOADGEN_ORDERER_CLIENT_ORDERER_CONNECTION_TLS_MODE="none"
  export SC_LOADGEN_SERVER_TLS_MODE="none"
  export SC_LOADGEN_ORDERER_CLIENT_SIDECAR_CLIENT_TLS_MODE="none"
fi

if [[ $ops == *"db"* ]]; then
  export POSTGRES_PASSWORD=yugabyte
  export POSTGRES_USER=yugabyte
  docker-entrypoint.sh postgres -p 5433 &
fi

if [[ $ops == *"orderer"* ]]; then
  "$BINS_PATH/mock"      start-orderer     --config "$CONFIGS_PATH/mock-orderer.yaml" &
fi

if [[ $ops == *"committer"* ]]; then
  "$BINS_PATH/committer" start-verifier    --config "$CONFIGS_PATH/verifier.yaml" &
  "$BINS_PATH/committer" start-vc          --config "$CONFIGS_PATH/vc.yaml" &
  "$BINS_PATH/committer" start-query       --config "$CONFIGS_PATH/query.yaml" &
  "$BINS_PATH/committer" start-coordinator --config "$CONFIGS_PATH/coordinator.yaml" &
  "$BINS_PATH/committer" start-sidecar     --config "$CONFIGS_PATH/sidecar.yaml" &
fi

if [[ $ops == *"loadgen"* ]]; then
  "$BINS_PATH/loadgen" start --config "$CONFIGS_PATH/loadgen.yaml" &
fi

# This just override's the postgres trap.
function cleanup() {
  jobs
}
trap 'cleanup' SIGINT

wait
echo "Process finished with status $?"
