//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: api/applicationpb/block_tx.proto

package applicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a transaction in the blockchain.
type Tx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of namespaces that define the transaction's scope.
	Namespaces []*TxNamespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// A list of endorsements.
	// IMPORTANT: This list MUST be the same size as the namespaces list.
	// The Endorsement at index i corresponds to the namespace at index i.
	Endorsements []*Endorsements `protobuf:"bytes,2,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
}

func (x *Tx) Reset() {
	*x = Tx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Tx) GetNamespaces() []*TxNamespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Tx) GetEndorsements() []*Endorsements {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

// Represents a namespace within a transaction.
type TxNamespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsId        string       `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`                      // The namespace ID.
	NsVersion   uint64       `protobuf:"varint,2,opt,name=ns_version,json=nsVersion,proto3" json:"ns_version,omitempty"`      // The version of the namespace.
	ReadsOnly   []*Read      `protobuf:"bytes,3,rep,name=reads_only,json=readsOnly,proto3" json:"reads_only,omitempty"`       // List of read only operations within the namespace.
	ReadWrites  []*ReadWrite `protobuf:"bytes,4,rep,name=read_writes,json=readWrites,proto3" json:"read_writes,omitempty"`    // List of read-write operations within the namespace.
	BlindWrites []*Write     `protobuf:"bytes,5,rep,name=blind_writes,json=blindWrites,proto3" json:"blind_writes,omitempty"` // List of blind write operations within the namespace.
}

func (x *TxNamespace) Reset() {
	*x = TxNamespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxNamespace) ProtoMessage() {}

func (x *TxNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxNamespace.ProtoReflect.Descriptor instead.
func (*TxNamespace) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxNamespace) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *TxNamespace) GetNsVersion() uint64 {
	if x != nil {
		return x.NsVersion
	}
	return 0
}

func (x *TxNamespace) GetReadsOnly() []*Read {
	if x != nil {
		return x.ReadsOnly
	}
	return nil
}

func (x *TxNamespace) GetReadWrites() []*ReadWrite {
	if x != nil {
		return x.ReadWrites
	}
	return nil
}

func (x *TxNamespace) GetBlindWrites() []*Write {
	if x != nil {
		return x.BlindWrites
	}
	return nil
}

// Represents a read operation.
type Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                // The key being read.
	Version *uint64 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"` // The version of the key being read. Nil version means it doesn't exist.
}

func (x *Read) Reset() {
	*x = Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{2}
}

func (x *Read) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Read) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

// Represents a read-write operation.
type ReadWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                // The key involved in the read-write operation.
	Version *uint64 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"` // The version of the key being read and written. Nil version means it doesn't exist.
	Value   []byte  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`            // The value associated with the key being written.
}

func (x *ReadWrite) Reset() {
	*x = ReadWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWrite) ProtoMessage() {}

func (x *ReadWrite) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWrite.ProtoReflect.Descriptor instead.
func (*ReadWrite) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{3}
}

func (x *ReadWrite) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReadWrite) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ReadWrite) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Represents a write operation.
type Write struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // The key being written.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The value associated with the key being written.
}

func (x *Write) Reset() {
	*x = Write{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{4}
}

func (x *Write) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Write) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Endorsements holds all the signatures that correspond to a single namespace
// in the transaction's namespaces list.
type Endorsements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of individual signatures for the corresponding namespace.
	EndorsementsWithIdentity []*EndorsementWithIdentity `protobuf:"bytes,1,rep,name=endorsements_with_identity,json=endorsementsWithIdentity,proto3" json:"endorsements_with_identity,omitempty"`
}

func (x *Endorsements) Reset() {
	*x = Endorsements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endorsements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorsements) ProtoMessage() {}

func (x *Endorsements) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorsements.ProtoReflect.Descriptor instead.
func (*Endorsements) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{5}
}

func (x *Endorsements) GetEndorsementsWithIdentity() []*EndorsementWithIdentity {
	if x != nil {
		return x.EndorsementsWithIdentity
	}
	return nil
}

// EndorsementWithIdentity bundles a single signature with the identity of its creator.
type EndorsementWithIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The actual cryptographic signature bytes.
	Endorsement []byte `protobuf:"bytes,1,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	// The identity of the creator who produced the signature, i.e., the endorsement.
	Identity *Identity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *EndorsementWithIdentity) Reset() {
	*x = EndorsementWithIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementWithIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementWithIdentity) ProtoMessage() {}

func (x *EndorsementWithIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementWithIdentity.ProtoReflect.Descriptor instead.
func (*EndorsementWithIdentity) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{6}
}

func (x *EndorsementWithIdentity) GetEndorsement() []byte {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

func (x *EndorsementWithIdentity) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The identifier of the associated membership service provider
	MspId string `protobuf:"bytes,1,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	// Types that are assignable to Creator:
	//
	//	*Identity_Certificate
	//	*Identity_CertificateId
	Creator isIdentity_Creator `protobuf_oneof:"creator"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_applicationpb_block_tx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_block_tx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_block_tx_proto_rawDescGZIP(), []int{7}
}

func (x *Identity) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

func (m *Identity) GetCreator() isIdentity_Creator {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (x *Identity) GetCertificate() []byte {
	if x, ok := x.GetCreator().(*Identity_Certificate); ok {
		return x.Certificate
	}
	return nil
}

func (x *Identity) GetCertificateId() string {
	if x, ok := x.GetCreator().(*Identity_CertificateId); ok {
		return x.CertificateId
	}
	return ""
}

type isIdentity_Creator interface {
	isIdentity_Creator()
}

type Identity_Certificate struct {
	// The full raw bytes of the creator's certificate (e.g., an X.509 certificate).
	Certificate []byte `protobuf:"bytes,2,opt,name=certificate,proto3,oneof"`
}

type Identity_CertificateId struct {
	// An identifier for a certificate that is pre-stored or known by the committer.
	CertificateId string `protobuf:"bytes,3,opt,name=certificate_id,json=certificateId,proto3,oneof"`
}

func (*Identity_Certificate) isIdentity_Creator() {}

func (*Identity_CertificateId) isIdentity_Creator() {}

var File_api_applicationpb_block_tx_proto protoreflect.FileDescriptor

var file_api_applicationpb_block_tx_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x70, 0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x22, 0x81, 0x01, 0x0a, 0x02, 0x54, 0x78, 0x12, 0x3a, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x0b, 0x54, 0x78, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x6e, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x73, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x73,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x6e, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x0a, 0x72, 0x65, 0x61,
	0x64, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x39, 0x0a,
	0x0b, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x0a, 0x72, 0x65,
	0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e,
	0x64, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x52, 0x0b, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x73, 0x22, 0x43, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x74, 0x0a, 0x0c, 0x45, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x64, 0x0a, 0x1a, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x64, 0x6f,
	0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x18, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x70, 0x0a,
	0x17, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x74, 0x68,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x79, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x73, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x70,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0e, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0d, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x49, 0x64, 0x42,
	0x09, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2d, 0x78, 0x2d, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_applicationpb_block_tx_proto_rawDescOnce sync.Once
	file_api_applicationpb_block_tx_proto_rawDescData = file_api_applicationpb_block_tx_proto_rawDesc
)

func file_api_applicationpb_block_tx_proto_rawDescGZIP() []byte {
	file_api_applicationpb_block_tx_proto_rawDescOnce.Do(func() {
		file_api_applicationpb_block_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_applicationpb_block_tx_proto_rawDescData)
	})
	return file_api_applicationpb_block_tx_proto_rawDescData
}

var file_api_applicationpb_block_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_applicationpb_block_tx_proto_goTypes = []interface{}{
	(*Tx)(nil),                      // 0: applicationpb.Tx
	(*TxNamespace)(nil),             // 1: applicationpb.TxNamespace
	(*Read)(nil),                    // 2: applicationpb.Read
	(*ReadWrite)(nil),               // 3: applicationpb.ReadWrite
	(*Write)(nil),                   // 4: applicationpb.Write
	(*Endorsements)(nil),            // 5: applicationpb.Endorsements
	(*EndorsementWithIdentity)(nil), // 6: applicationpb.EndorsementWithIdentity
	(*Identity)(nil),                // 7: applicationpb.Identity
}
var file_api_applicationpb_block_tx_proto_depIdxs = []int32{
	1, // 0: applicationpb.Tx.namespaces:type_name -> applicationpb.TxNamespace
	5, // 1: applicationpb.Tx.endorsements:type_name -> applicationpb.Endorsements
	2, // 2: applicationpb.TxNamespace.reads_only:type_name -> applicationpb.Read
	3, // 3: applicationpb.TxNamespace.read_writes:type_name -> applicationpb.ReadWrite
	4, // 4: applicationpb.TxNamespace.blind_writes:type_name -> applicationpb.Write
	6, // 5: applicationpb.Endorsements.endorsements_with_identity:type_name -> applicationpb.EndorsementWithIdentity
	7, // 6: applicationpb.EndorsementWithIdentity.identity:type_name -> applicationpb.Identity
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_applicationpb_block_tx_proto_init() }
func file_api_applicationpb_block_tx_proto_init() {
	if File_api_applicationpb_block_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_applicationpb_block_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxNamespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Write); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endorsements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementWithIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_applicationpb_block_tx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_applicationpb_block_tx_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_applicationpb_block_tx_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_api_applicationpb_block_tx_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Identity_Certificate)(nil),
		(*Identity_CertificateId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_applicationpb_block_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_applicationpb_block_tx_proto_goTypes,
		DependencyIndexes: file_api_applicationpb_block_tx_proto_depIdxs,
		MessageInfos:      file_api_applicationpb_block_tx_proto_msgTypes,
	}.Build()
	File_api_applicationpb_block_tx_proto = out.File
	file_api_applicationpb_block_tx_proto_rawDesc = nil
	file_api_applicationpb_block_tx_proto_goTypes = nil
	file_api_applicationpb_block_tx_proto_depIdxs = nil
}
