//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/applicationpb/config.proto

package applicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a namespace policy.
type NamespacePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Rule:
	//
	//	*NamespacePolicy_ThresholdRule
	//	*NamespacePolicy_MspRule
	Rule          isNamespacePolicy_Rule `protobuf_oneof:"rule"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacePolicy) Reset() {
	*x = NamespacePolicy{}
	mi := &file_api_applicationpb_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacePolicy) ProtoMessage() {}

func (x *NamespacePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacePolicy.ProtoReflect.Descriptor instead.
func (*NamespacePolicy) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_config_proto_rawDescGZIP(), []int{0}
}

func (x *NamespacePolicy) GetRule() isNamespacePolicy_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *NamespacePolicy) GetThresholdRule() *ThresholdRule {
	if x != nil {
		if x, ok := x.Rule.(*NamespacePolicy_ThresholdRule); ok {
			return x.ThresholdRule
		}
	}
	return nil
}

func (x *NamespacePolicy) GetMspRule() []byte {
	if x != nil {
		if x, ok := x.Rule.(*NamespacePolicy_MspRule); ok {
			return x.MspRule
		}
	}
	return nil
}

type isNamespacePolicy_Rule interface {
	isNamespacePolicy_Rule()
}

type NamespacePolicy_ThresholdRule struct {
	ThresholdRule *ThresholdRule `protobuf:"bytes,1,opt,name=threshold_rule,json=thresholdRule,proto3,oneof"`
}

type NamespacePolicy_MspRule struct {
	MspRule []byte `protobuf:"bytes,2,opt,name=msp_rule,json=mspRule,proto3,oneof"`
}

func (*NamespacePolicy_ThresholdRule) isNamespacePolicy_Rule() {}

func (*NamespacePolicy_MspRule) isNamespacePolicy_Rule() {}

// Represents a threshold signature rule.
type ThresholdRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`                        // The scheme for signature verification.
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // The public key for signature verification.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdRule) Reset() {
	*x = ThresholdRule{}
	mi := &file_api_applicationpb_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdRule) ProtoMessage() {}

func (x *ThresholdRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdRule.ProtoReflect.Descriptor instead.
func (*ThresholdRule) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_config_proto_rawDescGZIP(), []int{1}
}

func (x *ThresholdRule) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ThresholdRule) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// A batch of namespace policies.
type NamespacePolicies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyItem          `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacePolicies) Reset() {
	*x = NamespacePolicies{}
	mi := &file_api_applicationpb_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacePolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacePolicies) ProtoMessage() {}

func (x *NamespacePolicies) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacePolicies.ProtoReflect.Descriptor instead.
func (*NamespacePolicies) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_config_proto_rawDescGZIP(), []int{2}
}

func (x *NamespacePolicies) GetPolicies() []*PolicyItem {
	if x != nil {
		return x.Policies
	}
	return nil
}

// A namespace policy item with the update version.
type PolicyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Policy        []byte                 `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyItem) Reset() {
	*x = PolicyItem{}
	mi := &file_api_applicationpb_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyItem) ProtoMessage() {}

func (x *PolicyItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyItem.ProtoReflect.Descriptor instead.
func (*PolicyItem) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_config_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PolicyItem) GetPolicy() []byte {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *PolicyItem) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// The config TX envelope with the update version.
type ConfigTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      []byte                 `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigTransaction) Reset() {
	*x = ConfigTransaction{}
	mi := &file_api_applicationpb_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigTransaction) ProtoMessage() {}

func (x *ConfigTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicationpb_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigTransaction.ProtoReflect.Descriptor instead.
func (*ConfigTransaction) Descriptor() ([]byte, []int) {
	return file_api_applicationpb_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigTransaction) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ConfigTransaction) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_applicationpb_config_proto protoreflect.FileDescriptor

const file_api_applicationpb_config_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/applicationpb/config.proto\x12\rapplicationpb\"}\n" +
	"\x0fNamespacePolicy\x12E\n" +
	"\x0ethreshold_rule\x18\x01 \x01(\v2\x1c.applicationpb.ThresholdRuleH\x00R\rthresholdRule\x12\x1b\n" +
	"\bmsp_rule\x18\x02 \x01(\fH\x00R\amspRuleB\x06\n" +
	"\x04rule\"F\n" +
	"\rThresholdRule\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"J\n" +
	"\x11NamespacePolicies\x125\n" +
	"\bpolicies\x18\x01 \x03(\v2\x19.applicationpb.PolicyItemR\bpolicies\"\\\n" +
	"\n" +
	"PolicyItem\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06policy\x18\x02 \x01(\fR\x06policy\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"I\n" +
	"\x11ConfigTransaction\x12\x1a\n" +
	"\benvelope\x18\x01 \x01(\fR\benvelope\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversionB=Z;github.com/hyperledger/fabric-x-committer/api/applicationpbb\x06proto3"

var (
	file_api_applicationpb_config_proto_rawDescOnce sync.Once
	file_api_applicationpb_config_proto_rawDescData []byte
)

func file_api_applicationpb_config_proto_rawDescGZIP() []byte {
	file_api_applicationpb_config_proto_rawDescOnce.Do(func() {
		file_api_applicationpb_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_applicationpb_config_proto_rawDesc), len(file_api_applicationpb_config_proto_rawDesc)))
	})
	return file_api_applicationpb_config_proto_rawDescData
}

var file_api_applicationpb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_applicationpb_config_proto_goTypes = []any{
	(*NamespacePolicy)(nil),   // 0: applicationpb.NamespacePolicy
	(*ThresholdRule)(nil),     // 1: applicationpb.ThresholdRule
	(*NamespacePolicies)(nil), // 2: applicationpb.NamespacePolicies
	(*PolicyItem)(nil),        // 3: applicationpb.PolicyItem
	(*ConfigTransaction)(nil), // 4: applicationpb.ConfigTransaction
}
var file_api_applicationpb_config_proto_depIdxs = []int32{
	1, // 0: applicationpb.NamespacePolicy.threshold_rule:type_name -> applicationpb.ThresholdRule
	3, // 1: applicationpb.NamespacePolicies.policies:type_name -> applicationpb.PolicyItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_applicationpb_config_proto_init() }
func file_api_applicationpb_config_proto_init() {
	if File_api_applicationpb_config_proto != nil {
		return
	}
	file_api_applicationpb_config_proto_msgTypes[0].OneofWrappers = []any{
		(*NamespacePolicy_ThresholdRule)(nil),
		(*NamespacePolicy_MspRule)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_applicationpb_config_proto_rawDesc), len(file_api_applicationpb_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_applicationpb_config_proto_goTypes,
		DependencyIndexes: file_api_applicationpb_config_proto_depIdxs,
		MessageInfos:      file_api_applicationpb_config_proto_msgTypes,
	}.Build()
	File_api_applicationpb_config_proto = out.File
	file_api_applicationpb_config_proto_goTypes = nil
	file_api_applicationpb_config_proto_depIdxs = nil
}
