#!/usr/bin/env just --justfile

#########################
# Generate protos
#########################

PROTOC_CMD := "protoc"
PROTO_FLAGS := "--go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --proto_path=."

all: protos-token protos-coordinator protos-shardsservice protos-sigverification

protos-token:
    {{PROTOC_CMD}} \
    {{PROTO_FLAGS}} \
    ./token/token.proto

protos-coordinator:
    {{PROTOC_CMD}} \
    {{PROTO_FLAGS}} \
    ./coordinatorservice/coordinator_service.proto

protos-shardsservice:
    {{PROTOC_CMD}} \
    {{PROTO_FLAGS}} \
    ./shardsservice/shards.proto

protos-sigverification:
    {{PROTOC_CMD}} \
    {{PROTO_FLAGS}} \
    ./sigverification/verifier.proto

