// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: coordinatorservice/coordinator_service.proto

package coordinatorservice

import (
	sigverification "github.ibm.com/distributed-trust-research/scalable-committer/sigverification"
	token "github.ibm.com/distributed-trust-research/scalable-committer/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinatorservice_coordinator_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatorservice_coordinator_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_coordinatorservice_coordinator_service_proto_rawDescGZIP(), []int{0}
}

type TxValidationStatusBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxsValidationStatus []*TxValidationStatus `protobuf:"bytes,1,rep,name=txs_validation_status,json=txsValidationStatus,proto3" json:"txs_validation_status,omitempty"`
}

func (x *TxValidationStatusBatch) Reset() {
	*x = TxValidationStatusBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinatorservice_coordinator_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxValidationStatusBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxValidationStatusBatch) ProtoMessage() {}

func (x *TxValidationStatusBatch) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatorservice_coordinator_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxValidationStatusBatch.ProtoReflect.Descriptor instead.
func (*TxValidationStatusBatch) Descriptor() ([]byte, []int) {
	return file_coordinatorservice_coordinator_service_proto_rawDescGZIP(), []int{1}
}

func (x *TxValidationStatusBatch) GetTxsValidationStatus() []*TxValidationStatus {
	if x != nil {
		return x.TxsValidationStatus
	}
	return nil
}

type TxValidationStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum    uint64 `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	IsValid  bool   `protobuf:"varint,3,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
}

func (x *TxValidationStatus) Reset() {
	*x = TxValidationStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinatorservice_coordinator_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxValidationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxValidationStatus) ProtoMessage() {}

func (x *TxValidationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatorservice_coordinator_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxValidationStatus.ProtoReflect.Descriptor instead.
func (*TxValidationStatus) Descriptor() ([]byte, []int) {
	return file_coordinatorservice_coordinator_service_proto_rawDescGZIP(), []int{2}
}

func (x *TxValidationStatus) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *TxValidationStatus) GetTxNum() uint64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *TxValidationStatus) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_coordinatorservice_coordinator_service_proto protoreflect.FileDescriptor

var file_coordinatorservice_coordinator_service_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x11, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x73, 0x69, 0x67, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x75,
	0x0a, 0x17, 0x54, 0x78, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x5a, 0x0a, 0x15, 0x74, 0x78, 0x73,
	0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x78,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x13, 0x74, 0x78, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x63, 0x0a, 0x12, 0x54, 0x78, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x4e, 0x75, 0x6d, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x32, 0xa6, 0x01, 0x0a, 0x0b, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x45, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x50, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x78, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x62,
	0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x2d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2d, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2f, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coordinatorservice_coordinator_service_proto_rawDescOnce sync.Once
	file_coordinatorservice_coordinator_service_proto_rawDescData = file_coordinatorservice_coordinator_service_proto_rawDesc
)

func file_coordinatorservice_coordinator_service_proto_rawDescGZIP() []byte {
	file_coordinatorservice_coordinator_service_proto_rawDescOnce.Do(func() {
		file_coordinatorservice_coordinator_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_coordinatorservice_coordinator_service_proto_rawDescData)
	})
	return file_coordinatorservice_coordinator_service_proto_rawDescData
}

var file_coordinatorservice_coordinator_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_coordinatorservice_coordinator_service_proto_goTypes = []interface{}{
	(*Empty)(nil),                   // 0: coordinatorservice.Empty
	(*TxValidationStatusBatch)(nil), // 1: coordinatorservice.TxValidationStatusBatch
	(*TxValidationStatus)(nil),      // 2: coordinatorservice.TxValidationStatus
	(*sigverification.Key)(nil),     // 3: sigverification.Key
	(*token.Block)(nil),             // 4: token.Block
}
var file_coordinatorservice_coordinator_service_proto_depIdxs = []int32{
	2, // 0: coordinatorservice.TxValidationStatusBatch.txs_validation_status:type_name -> coordinatorservice.TxValidationStatus
	3, // 1: coordinatorservice.Coordinator.SetVerificationKey:input_type -> sigverification.Key
	4, // 2: coordinatorservice.Coordinator.BlockProcessing:input_type -> token.Block
	0, // 3: coordinatorservice.Coordinator.SetVerificationKey:output_type -> coordinatorservice.Empty
	1, // 4: coordinatorservice.Coordinator.BlockProcessing:output_type -> coordinatorservice.TxValidationStatusBatch
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coordinatorservice_coordinator_service_proto_init() }
func file_coordinatorservice_coordinator_service_proto_init() {
	if File_coordinatorservice_coordinator_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coordinatorservice_coordinator_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinatorservice_coordinator_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxValidationStatusBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinatorservice_coordinator_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxValidationStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coordinatorservice_coordinator_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinatorservice_coordinator_service_proto_goTypes,
		DependencyIndexes: file_coordinatorservice_coordinator_service_proto_depIdxs,
		MessageInfos:      file_coordinatorservice_coordinator_service_proto_msgTypes,
	}.Build()
	File_coordinatorservice_coordinator_service_proto = out.File
	file_coordinatorservice_coordinator_service_proto_rawDesc = nil
	file_coordinatorservice_coordinator_service_proto_goTypes = nil
	file_coordinatorservice_coordinator_service_proto_depIdxs = nil
}
