//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: api/protovcservice/vcservice.proto

package protovcservice

import (
	context "context"
	applicationpb "github.com/hyperledger/fabric-x-committer/api/applicationpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ValidationAndCommitService_StartValidateAndCommitStream_FullMethodName   = "/protovcservice.ValidationAndCommitService/StartValidateAndCommitStream"
	ValidationAndCommitService_SetLastCommittedBlockNumber_FullMethodName    = "/protovcservice.ValidationAndCommitService/SetLastCommittedBlockNumber"
	ValidationAndCommitService_GetNextBlockNumberToCommit_FullMethodName     = "/protovcservice.ValidationAndCommitService/GetNextBlockNumberToCommit"
	ValidationAndCommitService_GetTransactionsStatus_FullMethodName          = "/protovcservice.ValidationAndCommitService/GetTransactionsStatus"
	ValidationAndCommitService_GetNamespacePolicies_FullMethodName           = "/protovcservice.ValidationAndCommitService/GetNamespacePolicies"
	ValidationAndCommitService_GetConfigTransaction_FullMethodName           = "/protovcservice.ValidationAndCommitService/GetConfigTransaction"
	ValidationAndCommitService_SetupSystemTablesAndNamespaces_FullMethodName = "/protovcservice.ValidationAndCommitService/SetupSystemTablesAndNamespaces"
)

// ValidationAndCommitServiceClient is the client API for ValidationAndCommitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidationAndCommitServiceClient interface {
	StartValidateAndCommitStream(ctx context.Context, opts ...grpc.CallOption) (ValidationAndCommitService_StartValidateAndCommitStreamClient, error)
	SetLastCommittedBlockNumber(ctx context.Context, in *applicationpb.BlockInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetNextBlockNumberToCommit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*applicationpb.BlockInfo, error)
	GetTransactionsStatus(ctx context.Context, in *applicationpb.QueryStatus, opts ...grpc.CallOption) (*applicationpb.TransactionsStatus, error)
	GetNamespacePolicies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*applicationpb.NamespacePolicies, error)
	GetConfigTransaction(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*applicationpb.ConfigTransaction, error)
	SetupSystemTablesAndNamespaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type validationAndCommitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationAndCommitServiceClient(cc grpc.ClientConnInterface) ValidationAndCommitServiceClient {
	return &validationAndCommitServiceClient{cc}
}

func (c *validationAndCommitServiceClient) StartValidateAndCommitStream(ctx context.Context, opts ...grpc.CallOption) (ValidationAndCommitService_StartValidateAndCommitStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ValidationAndCommitService_ServiceDesc.Streams[0], ValidationAndCommitService_StartValidateAndCommitStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &validationAndCommitServiceStartValidateAndCommitStreamClient{stream}
	return x, nil
}

type ValidationAndCommitService_StartValidateAndCommitStreamClient interface {
	Send(*VcBatch) error
	Recv() (*applicationpb.TransactionsStatus, error)
	grpc.ClientStream
}

type validationAndCommitServiceStartValidateAndCommitStreamClient struct {
	grpc.ClientStream
}

func (x *validationAndCommitServiceStartValidateAndCommitStreamClient) Send(m *VcBatch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *validationAndCommitServiceStartValidateAndCommitStreamClient) Recv() (*applicationpb.TransactionsStatus, error) {
	m := new(applicationpb.TransactionsStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *validationAndCommitServiceClient) SetLastCommittedBlockNumber(ctx context.Context, in *applicationpb.BlockInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ValidationAndCommitService_SetLastCommittedBlockNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationAndCommitServiceClient) GetNextBlockNumberToCommit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*applicationpb.BlockInfo, error) {
	out := new(applicationpb.BlockInfo)
	err := c.cc.Invoke(ctx, ValidationAndCommitService_GetNextBlockNumberToCommit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationAndCommitServiceClient) GetTransactionsStatus(ctx context.Context, in *applicationpb.QueryStatus, opts ...grpc.CallOption) (*applicationpb.TransactionsStatus, error) {
	out := new(applicationpb.TransactionsStatus)
	err := c.cc.Invoke(ctx, ValidationAndCommitService_GetTransactionsStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationAndCommitServiceClient) GetNamespacePolicies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*applicationpb.NamespacePolicies, error) {
	out := new(applicationpb.NamespacePolicies)
	err := c.cc.Invoke(ctx, ValidationAndCommitService_GetNamespacePolicies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationAndCommitServiceClient) GetConfigTransaction(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*applicationpb.ConfigTransaction, error) {
	out := new(applicationpb.ConfigTransaction)
	err := c.cc.Invoke(ctx, ValidationAndCommitService_GetConfigTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationAndCommitServiceClient) SetupSystemTablesAndNamespaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ValidationAndCommitService_SetupSystemTablesAndNamespaces_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidationAndCommitServiceServer is the server API for ValidationAndCommitService service.
// All implementations must embed UnimplementedValidationAndCommitServiceServer
// for forward compatibility
type ValidationAndCommitServiceServer interface {
	StartValidateAndCommitStream(ValidationAndCommitService_StartValidateAndCommitStreamServer) error
	SetLastCommittedBlockNumber(context.Context, *applicationpb.BlockInfo) (*emptypb.Empty, error)
	GetNextBlockNumberToCommit(context.Context, *emptypb.Empty) (*applicationpb.BlockInfo, error)
	GetTransactionsStatus(context.Context, *applicationpb.QueryStatus) (*applicationpb.TransactionsStatus, error)
	GetNamespacePolicies(context.Context, *emptypb.Empty) (*applicationpb.NamespacePolicies, error)
	GetConfigTransaction(context.Context, *emptypb.Empty) (*applicationpb.ConfigTransaction, error)
	SetupSystemTablesAndNamespaces(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedValidationAndCommitServiceServer()
}

// UnimplementedValidationAndCommitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedValidationAndCommitServiceServer struct {
}

func (UnimplementedValidationAndCommitServiceServer) StartValidateAndCommitStream(ValidationAndCommitService_StartValidateAndCommitStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StartValidateAndCommitStream not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) SetLastCommittedBlockNumber(context.Context, *applicationpb.BlockInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLastCommittedBlockNumber not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) GetNextBlockNumberToCommit(context.Context, *emptypb.Empty) (*applicationpb.BlockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextBlockNumberToCommit not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) GetTransactionsStatus(context.Context, *applicationpb.QueryStatus) (*applicationpb.TransactionsStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionsStatus not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) GetNamespacePolicies(context.Context, *emptypb.Empty) (*applicationpb.NamespacePolicies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespacePolicies not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) GetConfigTransaction(context.Context, *emptypb.Empty) (*applicationpb.ConfigTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigTransaction not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) SetupSystemTablesAndNamespaces(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupSystemTablesAndNamespaces not implemented")
}
func (UnimplementedValidationAndCommitServiceServer) mustEmbedUnimplementedValidationAndCommitServiceServer() {
}

// UnsafeValidationAndCommitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationAndCommitServiceServer will
// result in compilation errors.
type UnsafeValidationAndCommitServiceServer interface {
	mustEmbedUnimplementedValidationAndCommitServiceServer()
}

func RegisterValidationAndCommitServiceServer(s grpc.ServiceRegistrar, srv ValidationAndCommitServiceServer) {
	s.RegisterService(&ValidationAndCommitService_ServiceDesc, srv)
}

func _ValidationAndCommitService_StartValidateAndCommitStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ValidationAndCommitServiceServer).StartValidateAndCommitStream(&validationAndCommitServiceStartValidateAndCommitStreamServer{stream})
}

type ValidationAndCommitService_StartValidateAndCommitStreamServer interface {
	Send(*applicationpb.TransactionsStatus) error
	Recv() (*VcBatch, error)
	grpc.ServerStream
}

type validationAndCommitServiceStartValidateAndCommitStreamServer struct {
	grpc.ServerStream
}

func (x *validationAndCommitServiceStartValidateAndCommitStreamServer) Send(m *applicationpb.TransactionsStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *validationAndCommitServiceStartValidateAndCommitStreamServer) Recv() (*VcBatch, error) {
	m := new(VcBatch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ValidationAndCommitService_SetLastCommittedBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(applicationpb.BlockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationAndCommitServiceServer).SetLastCommittedBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationAndCommitService_SetLastCommittedBlockNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationAndCommitServiceServer).SetLastCommittedBlockNumber(ctx, req.(*applicationpb.BlockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationAndCommitService_GetNextBlockNumberToCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationAndCommitServiceServer).GetNextBlockNumberToCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationAndCommitService_GetNextBlockNumberToCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationAndCommitServiceServer).GetNextBlockNumberToCommit(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationAndCommitService_GetTransactionsStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(applicationpb.QueryStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationAndCommitServiceServer).GetTransactionsStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationAndCommitService_GetTransactionsStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationAndCommitServiceServer).GetTransactionsStatus(ctx, req.(*applicationpb.QueryStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationAndCommitService_GetNamespacePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationAndCommitServiceServer).GetNamespacePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationAndCommitService_GetNamespacePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationAndCommitServiceServer).GetNamespacePolicies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationAndCommitService_GetConfigTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationAndCommitServiceServer).GetConfigTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationAndCommitService_GetConfigTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationAndCommitServiceServer).GetConfigTransaction(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationAndCommitService_SetupSystemTablesAndNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationAndCommitServiceServer).SetupSystemTablesAndNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationAndCommitService_SetupSystemTablesAndNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationAndCommitServiceServer).SetupSystemTablesAndNamespaces(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidationAndCommitService_ServiceDesc is the grpc.ServiceDesc for ValidationAndCommitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidationAndCommitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protovcservice.ValidationAndCommitService",
	HandlerType: (*ValidationAndCommitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLastCommittedBlockNumber",
			Handler:    _ValidationAndCommitService_SetLastCommittedBlockNumber_Handler,
		},
		{
			MethodName: "GetNextBlockNumberToCommit",
			Handler:    _ValidationAndCommitService_GetNextBlockNumberToCommit_Handler,
		},
		{
			MethodName: "GetTransactionsStatus",
			Handler:    _ValidationAndCommitService_GetTransactionsStatus_Handler,
		},
		{
			MethodName: "GetNamespacePolicies",
			Handler:    _ValidationAndCommitService_GetNamespacePolicies_Handler,
		},
		{
			MethodName: "GetConfigTransaction",
			Handler:    _ValidationAndCommitService_GetConfigTransaction_Handler,
		},
		{
			MethodName: "SetupSystemTablesAndNamespaces",
			Handler:    _ValidationAndCommitService_SetupSystemTablesAndNamespaces_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartValidateAndCommitStream",
			Handler:       _ValidationAndCommitService_StartValidateAndCommitStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/protovcservice/vcservice.proto",
}
