build: build-blockgen build-mockcoordinator

build-blockgen:
    go build -o bin/blockgen ./cmd/generator

build-mockcoordinator:
    go build -o bin/mockcoordinator ./cmd/mockcoordinator

build-sidecarclient os=("linux") arch=("amd64"):
    GOOS={{os}} GOARCH={{arch}} \
    go build -o bin/sidecarclient ./cmd/sidecarclient

test:
    go test -v ./...

clean:
    rm out/*.results

protos:
    protoc \
    --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    --proto_path=. \
    --proto_path=../protos \
    ./workload/expected_results.proto
