//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/committerpb/query.proto

package committerpb

import (
	applicationpb "github.com/hyperledger/fabric-x-committer/api/applicationpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsoLevel int32

const (
	IsoLevel_Serializable    IsoLevel = 0
	IsoLevel_RepeatableRead  IsoLevel = 1
	IsoLevel_ReadCommitted   IsoLevel = 2
	IsoLevel_ReadUncommitted IsoLevel = 3
)

// Enum value maps for IsoLevel.
var (
	IsoLevel_name = map[int32]string{
		0: "Serializable",
		1: "RepeatableRead",
		2: "ReadCommitted",
		3: "ReadUncommitted",
	}
	IsoLevel_value = map[string]int32{
		"Serializable":    0,
		"RepeatableRead":  1,
		"ReadCommitted":   2,
		"ReadUncommitted": 3,
	}
)

func (x IsoLevel) Enum() *IsoLevel {
	p := new(IsoLevel)
	*p = x
	return p
}

func (x IsoLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsoLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_committerpb_query_proto_enumTypes[0].Descriptor()
}

func (IsoLevel) Type() protoreflect.EnumType {
	return &file_api_committerpb_query_proto_enumTypes[0]
}

func (x IsoLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsoLevel.Descriptor instead.
func (IsoLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{0}
}

type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_api_committerpb_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{0}
}

func (x *View) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3,oneof" json:"view,omitempty"`
	Namespaces    []*QueryNamespace      `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_api_committerpb_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{1}
}

func (x *Query) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *Query) GetNamespaces() []*QueryNamespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type Rows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*RowsNamespace       `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rows) Reset() {
	*x = Rows{}
	mi := &file_api_committerpb_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rows) ProtoMessage() {}

func (x *Rows) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rows.ProtoReflect.Descriptor instead.
func (*Rows) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{2}
}

func (x *Rows) GetNamespaces() []*RowsNamespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ViewParameters struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IsoLevel            IsoLevel               `protobuf:"varint,1,opt,name=iso_level,json=isoLevel,proto3,enum=committerpb.IsoLevel" json:"iso_level,omitempty"`        // View's isolation level. Defaults to serializable.
	NonDeferrable       bool                   `protobuf:"varint,2,opt,name=nonDeferrable,proto3" json:"nonDeferrable,omitempty"`                                        // Do not defer errors. Defaults deferrable.
	TimeoutMilliseconds uint64                 `protobuf:"varint,3,opt,name=timeout_milliseconds,json=timeoutMilliseconds,proto3" json:"timeout_milliseconds,omitempty"` // View's timeout. Zero => maximal value
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ViewParameters) Reset() {
	*x = ViewParameters{}
	mi := &file_api_committerpb_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewParameters) ProtoMessage() {}

func (x *ViewParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewParameters.ProtoReflect.Descriptor instead.
func (*ViewParameters) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{3}
}

func (x *ViewParameters) GetIsoLevel() IsoLevel {
	if x != nil {
		return x.IsoLevel
	}
	return IsoLevel_Serializable
}

func (x *ViewParameters) GetNonDeferrable() bool {
	if x != nil {
		return x.NonDeferrable
	}
	return false
}

func (x *ViewParameters) GetTimeoutMilliseconds() uint64 {
	if x != nil {
		return x.TimeoutMilliseconds
	}
	return 0
}

type QueryNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsId          string                 `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNamespace) Reset() {
	*x = QueryNamespace{}
	mi := &file_api_committerpb_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNamespace) ProtoMessage() {}

func (x *QueryNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNamespace.ProtoReflect.Descriptor instead.
func (*QueryNamespace) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryNamespace) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *QueryNamespace) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RowsNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsId          string                 `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowsNamespace) Reset() {
	*x = RowsNamespace{}
	mi := &file_api_committerpb_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowsNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsNamespace) ProtoMessage() {}

func (x *RowsNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsNamespace.ProtoReflect.Descriptor instead.
func (*RowsNamespace) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{5}
}

func (x *RowsNamespace) GetNsId() string {
	if x != nil {
		return x.NsId
	}
	return ""
}

func (x *RowsNamespace) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_committerpb_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{6}
}

func (x *Row) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Row) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Row) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TxStatusQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3,oneof" json:"view,omitempty"`
	TxIds         []string               `protobuf:"bytes,2,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"` // List of transaction IDs.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusQuery) Reset() {
	*x = TxStatusQuery{}
	mi := &file_api_committerpb_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusQuery) ProtoMessage() {}

func (x *TxStatusQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusQuery.ProtoReflect.Descriptor instead.
func (*TxStatusQuery) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{7}
}

func (x *TxStatusQuery) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *TxStatusQuery) GetTxIds() []string {
	if x != nil {
		return x.TxIds
	}
	return nil
}

type TxStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TxStatus            `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusResponse) Reset() {
	*x = TxStatusResponse{}
	mi := &file_api_committerpb_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusResponse) ProtoMessage() {}

func (x *TxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusResponse.ProtoReflect.Descriptor instead.
func (*TxStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_committerpb_query_proto_rawDescGZIP(), []int{8}
}

func (x *TxStatusResponse) GetStatuses() []*TxStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_api_committerpb_query_proto protoreflect.FileDescriptor

const file_api_committerpb_query_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/committerpb/query.proto\x12\vcommitterpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1eapi/applicationpb/config.proto\x1a\x1capi/committerpb/status.proto\"\x16\n" +
	"\x04View\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x05Query\x12*\n" +
	"\x04view\x18\x01 \x01(\v2\x11.committerpb.ViewH\x00R\x04view\x88\x01\x01\x12;\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\v2\x1b.committerpb.QueryNamespaceR\n" +
	"namespacesB\a\n" +
	"\x05_view\"B\n" +
	"\x04Rows\x12:\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x1a.committerpb.RowsNamespaceR\n" +
	"namespaces\"\x9d\x01\n" +
	"\x0eViewParameters\x122\n" +
	"\tiso_level\x18\x01 \x01(\x0e2\x15.committerpb.IsoLevelR\bisoLevel\x12$\n" +
	"\rnonDeferrable\x18\x02 \x01(\bR\rnonDeferrable\x121\n" +
	"\x14timeout_milliseconds\x18\x03 \x01(\x04R\x13timeoutMilliseconds\"9\n" +
	"\x0eQueryNamespace\x12\x13\n" +
	"\x05ns_id\x18\x01 \x01(\tR\x04nsId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"J\n" +
	"\rRowsNamespace\x12\x13\n" +
	"\x05ns_id\x18\x01 \x01(\tR\x04nsId\x12$\n" +
	"\x04rows\x18\x02 \x03(\v2\x10.committerpb.RowR\x04rows\"G\n" +
	"\x03Row\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"[\n" +
	"\rTxStatusQuery\x12*\n" +
	"\x04view\x18\x01 \x01(\v2\x11.committerpb.ViewH\x00R\x04view\x88\x01\x01\x12\x15\n" +
	"\x06tx_ids\x18\x02 \x03(\tR\x05txIdsB\a\n" +
	"\x05_view\"E\n" +
	"\x10TxStatusResponse\x121\n" +
	"\bstatuses\x18\x01 \x03(\v2\x15.committerpb.TxStatusR\bstatuses*X\n" +
	"\bIsoLevel\x12\x10\n" +
	"\fSerializable\x10\x00\x12\x12\n" +
	"\x0eRepeatableRead\x10\x01\x12\x11\n" +
	"\rReadCommitted\x10\x02\x12\x13\n" +
	"\x0fReadUncommitted\x10\x032\xb1\x03\n" +
	"\fQueryService\x122\n" +
	"\aGetRows\x12\x12.committerpb.Query\x1a\x11.committerpb.Rows\"\x00\x12=\n" +
	"\tBeginView\x12\x1b.committerpb.ViewParameters\x1a\x11.committerpb.View\"\x00\x121\n" +
	"\aEndView\x12\x11.committerpb.View\x1a\x11.committerpb.View\"\x00\x12R\n" +
	"\x14GetNamespacePolicies\x12\x16.google.protobuf.Empty\x1a .applicationpb.NamespacePolicies\"\x00\x12R\n" +
	"\x14GetConfigTransaction\x12\x16.google.protobuf.Empty\x1a .applicationpb.ConfigTransaction\"\x00\x12S\n" +
	"\x14GetTransactionStatus\x12\x1a.committerpb.TxStatusQuery\x1a\x1d.committerpb.TxStatusResponse\"\x00B;Z9github.com/hyperledger/fabric-x-committer/api/committerpbb\x06proto3"

var (
	file_api_committerpb_query_proto_rawDescOnce sync.Once
	file_api_committerpb_query_proto_rawDescData []byte
)

func file_api_committerpb_query_proto_rawDescGZIP() []byte {
	file_api_committerpb_query_proto_rawDescOnce.Do(func() {
		file_api_committerpb_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_query_proto_rawDesc), len(file_api_committerpb_query_proto_rawDesc)))
	})
	return file_api_committerpb_query_proto_rawDescData
}

var file_api_committerpb_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_committerpb_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_committerpb_query_proto_goTypes = []any{
	(IsoLevel)(0),                           // 0: committerpb.IsoLevel
	(*View)(nil),                            // 1: committerpb.View
	(*Query)(nil),                           // 2: committerpb.Query
	(*Rows)(nil),                            // 3: committerpb.Rows
	(*ViewParameters)(nil),                  // 4: committerpb.ViewParameters
	(*QueryNamespace)(nil),                  // 5: committerpb.QueryNamespace
	(*RowsNamespace)(nil),                   // 6: committerpb.RowsNamespace
	(*Row)(nil),                             // 7: committerpb.Row
	(*TxStatusQuery)(nil),                   // 8: committerpb.TxStatusQuery
	(*TxStatusResponse)(nil),                // 9: committerpb.TxStatusResponse
	(*TxStatus)(nil),                        // 10: committerpb.TxStatus
	(*emptypb.Empty)(nil),                   // 11: google.protobuf.Empty
	(*applicationpb.NamespacePolicies)(nil), // 12: applicationpb.NamespacePolicies
	(*applicationpb.ConfigTransaction)(nil), // 13: applicationpb.ConfigTransaction
}
var file_api_committerpb_query_proto_depIdxs = []int32{
	1,  // 0: committerpb.Query.view:type_name -> committerpb.View
	5,  // 1: committerpb.Query.namespaces:type_name -> committerpb.QueryNamespace
	6,  // 2: committerpb.Rows.namespaces:type_name -> committerpb.RowsNamespace
	0,  // 3: committerpb.ViewParameters.iso_level:type_name -> committerpb.IsoLevel
	7,  // 4: committerpb.RowsNamespace.rows:type_name -> committerpb.Row
	1,  // 5: committerpb.TxStatusQuery.view:type_name -> committerpb.View
	10, // 6: committerpb.TxStatusResponse.statuses:type_name -> committerpb.TxStatus
	2,  // 7: committerpb.QueryService.GetRows:input_type -> committerpb.Query
	4,  // 8: committerpb.QueryService.BeginView:input_type -> committerpb.ViewParameters
	1,  // 9: committerpb.QueryService.EndView:input_type -> committerpb.View
	11, // 10: committerpb.QueryService.GetNamespacePolicies:input_type -> google.protobuf.Empty
	11, // 11: committerpb.QueryService.GetConfigTransaction:input_type -> google.protobuf.Empty
	8,  // 12: committerpb.QueryService.GetTransactionStatus:input_type -> committerpb.TxStatusQuery
	3,  // 13: committerpb.QueryService.GetRows:output_type -> committerpb.Rows
	1,  // 14: committerpb.QueryService.BeginView:output_type -> committerpb.View
	1,  // 15: committerpb.QueryService.EndView:output_type -> committerpb.View
	12, // 16: committerpb.QueryService.GetNamespacePolicies:output_type -> applicationpb.NamespacePolicies
	13, // 17: committerpb.QueryService.GetConfigTransaction:output_type -> applicationpb.ConfigTransaction
	9,  // 18: committerpb.QueryService.GetTransactionStatus:output_type -> committerpb.TxStatusResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_committerpb_query_proto_init() }
func file_api_committerpb_query_proto_init() {
	if File_api_committerpb_query_proto != nil {
		return
	}
	file_api_committerpb_status_proto_init()
	file_api_committerpb_query_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_committerpb_query_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_query_proto_rawDesc), len(file_api_committerpb_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_committerpb_query_proto_goTypes,
		DependencyIndexes: file_api_committerpb_query_proto_depIdxs,
		EnumInfos:         file_api_committerpb_query_proto_enumTypes,
		MessageInfos:      file_api_committerpb_query_proto_msgTypes,
	}.Build()
	File_api_committerpb_query_proto = out.File
	file_api_committerpb_query_proto_goTypes = nil
	file_api_committerpb_query_proto_depIdxs = nil
}
