//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: api/committerpb/ref.proto

package committerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The TX reference with respect to the block generated by the orderer.
type TxRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"` // The block number.
	TxNum    uint32 `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`          // Transaction number within the block
	TxId     string `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`              // Transaction ID within the block.
}

func (x *TxRef) Reset() {
	*x = TxRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_committerpb_ref_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRef) ProtoMessage() {}

func (x *TxRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_ref_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRef.ProtoReflect.Descriptor instead.
func (*TxRef) Descriptor() ([]byte, []int) {
	return file_api_committerpb_ref_proto_rawDescGZIP(), []int{0}
}

func (x *TxRef) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *TxRef) GetTxNum() uint32 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

func (x *TxRef) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_api_committerpb_ref_proto protoreflect.FileDescriptor

var file_api_committerpb_ref_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x70,
	0x62, 0x2f, 0x72, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x70, 0x62, 0x22, 0x50, 0x0a, 0x05, 0x54, 0x78, 0x52, 0x65,
	0x66, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x78, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x78, 0x4e, 0x75, 0x6d, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2d, 0x78, 0x2d, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_committerpb_ref_proto_rawDescOnce sync.Once
	file_api_committerpb_ref_proto_rawDescData = file_api_committerpb_ref_proto_rawDesc
)

func file_api_committerpb_ref_proto_rawDescGZIP() []byte {
	file_api_committerpb_ref_proto_rawDescOnce.Do(func() {
		file_api_committerpb_ref_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_committerpb_ref_proto_rawDescData)
	})
	return file_api_committerpb_ref_proto_rawDescData
}

var file_api_committerpb_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_committerpb_ref_proto_goTypes = []interface{}{
	(*TxRef)(nil), // 0: committerpb.TxRef
}
var file_api_committerpb_ref_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_committerpb_ref_proto_init() }
func file_api_committerpb_ref_proto_init() {
	if File_api_committerpb_ref_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_committerpb_ref_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_committerpb_ref_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_committerpb_ref_proto_goTypes,
		DependencyIndexes: file_api_committerpb_ref_proto_depIdxs,
		MessageInfos:      file_api_committerpb_ref_proto_msgTypes,
	}.Build()
	File_api_committerpb_ref_proto = out.File
	file_api_committerpb_ref_proto_rawDesc = nil
	file_api_committerpb_ref_proto_goTypes = nil
	file_api_committerpb_ref_proto_depIdxs = nil
}
