# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a partial template. It contains only the orderer client configurations.
# It should be complimented by the common load generator configuration.

orderer-client:
  orderer:
    fault-tolerance-level: BFT
    last-known-config-block-path: "{{ .Policy.ArtifactsPath }}/config-block.pb.bin"
    tls:
      mode: {{ .ClientTLS.Mode }}
      cert-path: {{ .ClientTLS.CertPath }}
      key-path: {{ .ClientTLS.KeyPath }}
      common-ca-cert-paths:
        {{- range .ClientTLS.CACertPaths }}
        - {{ . }}
        {{- end }}
    identity:
      msp-id: peer-org-0
      msp-dir: {{ .Policy.ArtifactsPath }}/peerOrganizations/peer-org-0/users/client@peer-org-0.com/msp
      bccsp:
        Default: SW
        SW:
          Security: 256
          Hash: SHA2
  broadcast-parallelism: 5
