#!/bin/bash

binDir="bin"
COORDINATOR_MAIN="PATH TO COORDINATOR MAIN.GO"
COORDINATOR_BIN="coordinator"
SHARDSSERVICE_MAIN="PATH TO SHARDSSERVICE MAIN.GO"
SHARDSSERVICE_BIN="shardsservice"
SIGVERIFICATION_MAIN="PATH TO SIGVERIFICATION MAIN.GO"
SIGVERIFICATION_BIN="sigverification"

mkdir -p ${binDir}

go build -o "${binDir}/${COORDINATOR_BIN}" ${COORDINATOR_MAIN}
go build -o "${binDir}/${SHARDSSERVICE_BIN}" ${SHARDSSERVICE_MAIN}
go build -o "${binDir}/${SIGVERIFICATION_BIN}" ${SIGVERIFICATION_MAIN}