//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/servicepb/common.proto

package servicepb

import (
	applicationpb "github.com/hyperledger/fabric-x-committer/api/applicationpb"
	committerpb "github.com/hyperledger/fabric-x-committer/api/committerpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A block reference with respect to the block generated by the orderer.
type BlockRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_api_servicepb_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_api_servicepb_common_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRef) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

// A committer's representation of a TX in the blockchain.
type TxWithRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *committerpb.TxRef     `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`         // The TX reference.
	Content       *applicationpb.Tx      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // The TX content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxWithRef) Reset() {
	*x = TxWithRef{}
	mi := &file_api_servicepb_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxWithRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxWithRef) ProtoMessage() {}

func (x *TxWithRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxWithRef.ProtoReflect.Descriptor instead.
func (*TxWithRef) Descriptor() ([]byte, []int) {
	return file_api_servicepb_common_proto_rawDescGZIP(), []int{1}
}

func (x *TxWithRef) GetRef() *committerpb.TxRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *TxWithRef) GetContent() *applicationpb.Tx {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_api_servicepb_common_proto protoreflect.FileDescriptor

const file_api_servicepb_common_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/servicepb/common.proto\x12\tservicepb\x1a api/applicationpb/block_tx.proto\x1a\x19api/committerpb/ref.proto\"\"\n" +
	"\bBlockRef\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"^\n" +
	"\tTxWithRef\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.committerpb.TxRefR\x03ref\x12+\n" +
	"\acontent\x18\x02 \x01(\v2\x11.applicationpb.TxR\acontentB9Z7github.com/hyperledger/fabric-x-committer/api/servicepbb\x06proto3"

var (
	file_api_servicepb_common_proto_rawDescOnce sync.Once
	file_api_servicepb_common_proto_rawDescData []byte
)

func file_api_servicepb_common_proto_rawDescGZIP() []byte {
	file_api_servicepb_common_proto_rawDescOnce.Do(func() {
		file_api_servicepb_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_servicepb_common_proto_rawDesc), len(file_api_servicepb_common_proto_rawDesc)))
	})
	return file_api_servicepb_common_proto_rawDescData
}

var file_api_servicepb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_servicepb_common_proto_goTypes = []any{
	(*BlockRef)(nil),          // 0: servicepb.BlockRef
	(*TxWithRef)(nil),         // 1: servicepb.TxWithRef
	(*committerpb.TxRef)(nil), // 2: committerpb.TxRef
	(*applicationpb.Tx)(nil),  // 3: applicationpb.Tx
}
var file_api_servicepb_common_proto_depIdxs = []int32{
	2, // 0: servicepb.TxWithRef.ref:type_name -> committerpb.TxRef
	3, // 1: servicepb.TxWithRef.content:type_name -> applicationpb.Tx
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_servicepb_common_proto_init() }
func file_api_servicepb_common_proto_init() {
	if File_api_servicepb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_servicepb_common_proto_rawDesc), len(file_api_servicepb_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_servicepb_common_proto_goTypes,
		DependencyIndexes: file_api_servicepb_common_proto_depIdxs,
		MessageInfos:      file_api_servicepb_common_proto_msgTypes,
	}.Build()
	File_api_servicepb_common_proto = out.File
	file_api_servicepb_common_proto_goTypes = nil
	file_api_servicepb_common_proto_depIdxs = nil
}
