//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/servicepb/coordinator.proto

package servicepb

import (
	applicationpb "github.com/hyperledger/fabric-x-committer/api/applicationpb"
	committerpb "github.com/hyperledger/fabric-x-committer/api/committerpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A committer's representation of a block in the blockchain.
type CoordinatorBatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Txs           []*TxWithRef            `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`           // List of transactions within the block.
	Rejected      []*committerpb.TxStatus `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected,omitempty"` // Rejected transactions.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorBatch) Reset() {
	*x = CoordinatorBatch{}
	mi := &file_api_servicepb_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorBatch) ProtoMessage() {}

func (x *CoordinatorBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorBatch.ProtoReflect.Descriptor instead.
func (*CoordinatorBatch) Descriptor() ([]byte, []int) {
	return file_api_servicepb_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatorBatch) GetTxs() []*TxWithRef {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *CoordinatorBatch) GetRejected() []*committerpb.TxStatus {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type WaitingTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitingTransactions) Reset() {
	*x = WaitingTransactions{}
	mi := &file_api_servicepb_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitingTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingTransactions) ProtoMessage() {}

func (x *WaitingTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingTransactions.ProtoReflect.Descriptor instead.
func (*WaitingTransactions) Descriptor() ([]byte, []int) {
	return file_api_servicepb_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *WaitingTransactions) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_servicepb_coordinator_proto protoreflect.FileDescriptor

const file_api_servicepb_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/servicepb/coordinator.proto\x12\tservicepb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1eapi/applicationpb/config.proto\x1a\x1capi/committerpb/status.proto\x1a\x1aapi/servicepb/common.proto\"m\n" +
	"\x10CoordinatorBatch\x12&\n" +
	"\x03txs\x18\x01 \x03(\v2\x14.servicepb.TxWithRefR\x03txs\x121\n" +
	"\brejected\x18\x02 \x03(\v2\x15.committerpb.TxStatusR\brejected\"+\n" +
	"\x13WaitingTransactions\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xf9\x03\n" +
	"\vCoordinator\x12N\n" +
	"\x0fBlockProcessing\x12\x1b.servicepb.CoordinatorBatch\x1a\x1a.committerpb.TxStatusBatch(\x010\x01\x12L\n" +
	"\x1bSetLastCommittedBlockNumber\x12\x13.servicepb.BlockRef\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x1aGetNextBlockNumberToCommit\x12\x16.google.protobuf.Empty\x1a\x13.servicepb.BlockRef\"\x00\x12K\n" +
	"\x15GetTransactionsStatus\x12\x16.servicepb.QueryStatus\x1a\x1a.committerpb.TxStatusBatch\x12R\n" +
	"\x14GetConfigTransaction\x12\x16.google.protobuf.Empty\x1a .applicationpb.ConfigTransaction\"\x00\x12^\n" +
	"$NumberOfWaitingTransactionsForStatus\x12\x16.google.protobuf.Empty\x1a\x1e.servicepb.WaitingTransactionsB9Z7github.com/hyperledger/fabric-x-committer/api/servicepbb\x06proto3"

var (
	file_api_servicepb_coordinator_proto_rawDescOnce sync.Once
	file_api_servicepb_coordinator_proto_rawDescData []byte
)

func file_api_servicepb_coordinator_proto_rawDescGZIP() []byte {
	file_api_servicepb_coordinator_proto_rawDescOnce.Do(func() {
		file_api_servicepb_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_servicepb_coordinator_proto_rawDesc), len(file_api_servicepb_coordinator_proto_rawDesc)))
	})
	return file_api_servicepb_coordinator_proto_rawDescData
}

var file_api_servicepb_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_servicepb_coordinator_proto_goTypes = []any{
	(*CoordinatorBatch)(nil),                // 0: servicepb.CoordinatorBatch
	(*WaitingTransactions)(nil),             // 1: servicepb.WaitingTransactions
	(*TxWithRef)(nil),                       // 2: servicepb.TxWithRef
	(*committerpb.TxStatus)(nil),            // 3: committerpb.TxStatus
	(*BlockRef)(nil),                        // 4: servicepb.BlockRef
	(*emptypb.Empty)(nil),                   // 5: google.protobuf.Empty
	(*QueryStatus)(nil),                     // 6: servicepb.QueryStatus
	(*committerpb.TxStatusBatch)(nil),       // 7: committerpb.TxStatusBatch
	(*applicationpb.ConfigTransaction)(nil), // 8: applicationpb.ConfigTransaction
}
var file_api_servicepb_coordinator_proto_depIdxs = []int32{
	2, // 0: servicepb.CoordinatorBatch.txs:type_name -> servicepb.TxWithRef
	3, // 1: servicepb.CoordinatorBatch.rejected:type_name -> committerpb.TxStatus
	0, // 2: servicepb.Coordinator.BlockProcessing:input_type -> servicepb.CoordinatorBatch
	4, // 3: servicepb.Coordinator.SetLastCommittedBlockNumber:input_type -> servicepb.BlockRef
	5, // 4: servicepb.Coordinator.GetNextBlockNumberToCommit:input_type -> google.protobuf.Empty
	6, // 5: servicepb.Coordinator.GetTransactionsStatus:input_type -> servicepb.QueryStatus
	5, // 6: servicepb.Coordinator.GetConfigTransaction:input_type -> google.protobuf.Empty
	5, // 7: servicepb.Coordinator.NumberOfWaitingTransactionsForStatus:input_type -> google.protobuf.Empty
	7, // 8: servicepb.Coordinator.BlockProcessing:output_type -> committerpb.TxStatusBatch
	5, // 9: servicepb.Coordinator.SetLastCommittedBlockNumber:output_type -> google.protobuf.Empty
	4, // 10: servicepb.Coordinator.GetNextBlockNumberToCommit:output_type -> servicepb.BlockRef
	7, // 11: servicepb.Coordinator.GetTransactionsStatus:output_type -> committerpb.TxStatusBatch
	8, // 12: servicepb.Coordinator.GetConfigTransaction:output_type -> applicationpb.ConfigTransaction
	1, // 13: servicepb.Coordinator.NumberOfWaitingTransactionsForStatus:output_type -> servicepb.WaitingTransactions
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_servicepb_coordinator_proto_init() }
func file_api_servicepb_coordinator_proto_init() {
	if File_api_servicepb_coordinator_proto != nil {
		return
	}
	file_api_servicepb_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_servicepb_coordinator_proto_rawDesc), len(file_api_servicepb_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_servicepb_coordinator_proto_goTypes,
		DependencyIndexes: file_api_servicepb_coordinator_proto_depIdxs,
		MessageInfos:      file_api_servicepb_coordinator_proto_msgTypes,
	}.Build()
	File_api_servicepb_coordinator_proto = out.File
	file_api_servicepb_coordinator_proto_goTypes = nil
	file_api_servicepb_coordinator_proto_depIdxs = nil
}
