//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/servicepb/loadgen.proto

package servicepb

import (
	applicationpb "github.com/hyperledger/fabric-x-committer/api/applicationpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadGenBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []*LoadGenTx           `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGenBatch) Reset() {
	*x = LoadGenBatch{}
	mi := &file_api_servicepb_loadgen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGenBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGenBatch) ProtoMessage() {}

func (x *LoadGenBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_loadgen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGenBatch.ProtoReflect.Descriptor instead.
func (*LoadGenBatch) Descriptor() ([]byte, []int) {
	return file_api_servicepb_loadgen_proto_rawDescGZIP(), []int{0}
}

func (x *LoadGenBatch) GetTx() []*LoadGenTx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type LoadGenTx struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tx                 *applicationpb.Tx      `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	EnvelopePayload    []byte                 `protobuf:"bytes,3,opt,name=envelope_payload,json=envelopePayload,proto3" json:"envelope_payload,omitempty"`
	EnvelopeSignature  []byte                 `protobuf:"bytes,4,opt,name=envelope_signature,json=envelopeSignature,proto3" json:"envelope_signature,omitempty"`
	SerializedEnvelope []byte                 `protobuf:"bytes,5,opt,name=serialized_envelope,json=serializedEnvelope,proto3" json:"serialized_envelope,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoadGenTx) Reset() {
	*x = LoadGenTx{}
	mi := &file_api_servicepb_loadgen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGenTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGenTx) ProtoMessage() {}

func (x *LoadGenTx) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_loadgen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGenTx.ProtoReflect.Descriptor instead.
func (*LoadGenTx) Descriptor() ([]byte, []int) {
	return file_api_servicepb_loadgen_proto_rawDescGZIP(), []int{1}
}

func (x *LoadGenTx) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadGenTx) GetTx() *applicationpb.Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LoadGenTx) GetEnvelopePayload() []byte {
	if x != nil {
		return x.EnvelopePayload
	}
	return nil
}

func (x *LoadGenTx) GetEnvelopeSignature() []byte {
	if x != nil {
		return x.EnvelopeSignature
	}
	return nil
}

func (x *LoadGenTx) GetSerializedEnvelope() []byte {
	if x != nil {
		return x.SerializedEnvelope
	}
	return nil
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_api_servicepb_loadgen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_loadgen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_api_servicepb_loadgen_proto_rawDescGZIP(), []int{2}
}

func (x *Limit) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_api_servicepb_loadgen_proto protoreflect.FileDescriptor

const file_api_servicepb_loadgen_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/servicepb/loadgen.proto\x12\tservicepb\x1a\x1bgoogle/protobuf/empty.proto\x1a api/applicationpb/block_tx.proto\"4\n" +
	"\fLoadGenBatch\x12$\n" +
	"\x02tx\x18\x01 \x03(\v2\x14.servicepb.LoadGenTxR\x02tx\"\xc9\x01\n" +
	"\tLoadGenTx\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x02tx\x18\x02 \x01(\v2\x11.applicationpb.TxR\x02tx\x12)\n" +
	"\x10envelope_payload\x18\x03 \x01(\fR\x0fenvelopePayload\x12-\n" +
	"\x12envelope_signature\x18\x04 \x01(\fR\x11envelopeSignature\x12/\n" +
	"\x13serialized_envelope\x18\x05 \x01(\fR\x12serializedEnvelope\"\x1b\n" +
	"\x05Limit\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate2\xc0\x01\n" +
	"\x0eLoadGenService\x12@\n" +
	"\vAppendBatch\x12\x17.servicepb.LoadGenBatch\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\bGetLimit\x12\x16.google.protobuf.Empty\x1a\x10.servicepb.Limit\"\x00\x124\n" +
	"\bSetLimit\x12\x10.servicepb.Limit\x1a\x16.google.protobuf.EmptyB9Z7github.com/hyperledger/fabric-x-committer/api/servicepbb\x06proto3"

var (
	file_api_servicepb_loadgen_proto_rawDescOnce sync.Once
	file_api_servicepb_loadgen_proto_rawDescData []byte
)

func file_api_servicepb_loadgen_proto_rawDescGZIP() []byte {
	file_api_servicepb_loadgen_proto_rawDescOnce.Do(func() {
		file_api_servicepb_loadgen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_servicepb_loadgen_proto_rawDesc), len(file_api_servicepb_loadgen_proto_rawDesc)))
	})
	return file_api_servicepb_loadgen_proto_rawDescData
}

var file_api_servicepb_loadgen_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_servicepb_loadgen_proto_goTypes = []any{
	(*LoadGenBatch)(nil),     // 0: servicepb.LoadGenBatch
	(*LoadGenTx)(nil),        // 1: servicepb.LoadGenTx
	(*Limit)(nil),            // 2: servicepb.Limit
	(*applicationpb.Tx)(nil), // 3: applicationpb.Tx
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_api_servicepb_loadgen_proto_depIdxs = []int32{
	1, // 0: servicepb.LoadGenBatch.tx:type_name -> servicepb.LoadGenTx
	3, // 1: servicepb.LoadGenTx.tx:type_name -> applicationpb.Tx
	0, // 2: servicepb.LoadGenService.AppendBatch:input_type -> servicepb.LoadGenBatch
	4, // 3: servicepb.LoadGenService.GetLimit:input_type -> google.protobuf.Empty
	2, // 4: servicepb.LoadGenService.SetLimit:input_type -> servicepb.Limit
	4, // 5: servicepb.LoadGenService.AppendBatch:output_type -> google.protobuf.Empty
	2, // 6: servicepb.LoadGenService.GetLimit:output_type -> servicepb.Limit
	4, // 7: servicepb.LoadGenService.SetLimit:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_servicepb_loadgen_proto_init() }
func file_api_servicepb_loadgen_proto_init() {
	if File_api_servicepb_loadgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_servicepb_loadgen_proto_rawDesc), len(file_api_servicepb_loadgen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_servicepb_loadgen_proto_goTypes,
		DependencyIndexes: file_api_servicepb_loadgen_proto_depIdxs,
		MessageInfos:      file_api_servicepb_loadgen_proto_msgTypes,
	}.Build()
	File_api_servicepb_loadgen_proto = out.File
	file_api_servicepb_loadgen_proto_goTypes = nil
	file_api_servicepb_loadgen_proto_depIdxs = nil
}
