//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/servicepb/verifier.proto

package servicepb

import (
	context "context"
	committerpb "github.com/hyperledger/fabric-x-common/api/committerpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Verifier_StartStream_FullMethodName = "/servicepb.Verifier/StartStream"
)

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifierClient interface {
	StartStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VerifierBatch, committerpb.TxStatusBatch], error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) StartStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VerifierBatch, committerpb.TxStatusBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Verifier_ServiceDesc.Streams[0], Verifier_StartStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VerifierBatch, committerpb.TxStatusBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Verifier_StartStreamClient = grpc.BidiStreamingClient[VerifierBatch, committerpb.TxStatusBatch]

// VerifierServer is the server API for Verifier service.
// All implementations must embed UnimplementedVerifierServer
// for forward compatibility.
type VerifierServer interface {
	StartStream(grpc.BidiStreamingServer[VerifierBatch, committerpb.TxStatusBatch]) error
	mustEmbedUnimplementedVerifierServer()
}

// UnimplementedVerifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifierServer struct{}

func (UnimplementedVerifierServer) StartStream(grpc.BidiStreamingServer[VerifierBatch, committerpb.TxStatusBatch]) error {
	return status.Error(codes.Unimplemented, "method StartStream not implemented")
}
func (UnimplementedVerifierServer) mustEmbedUnimplementedVerifierServer() {}
func (UnimplementedVerifierServer) testEmbeddedByValue()                  {}

// UnsafeVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierServer will
// result in compilation errors.
type UnsafeVerifierServer interface {
	mustEmbedUnimplementedVerifierServer()
}

func RegisterVerifierServer(s grpc.ServiceRegistrar, srv VerifierServer) {
	// If the following call panics, it indicates UnimplementedVerifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Verifier_ServiceDesc, srv)
}

func _Verifier_StartStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VerifierServer).StartStream(&grpc.GenericServerStream[VerifierBatch, committerpb.TxStatusBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Verifier_StartStreamServer = grpc.BidiStreamingServer[VerifierBatch, committerpb.TxStatusBatch]

// Verifier_ServiceDesc is the grpc.ServiceDesc for Verifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Verifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartStream",
			Handler:       _Verifier_StartStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/servicepb/verifier.proto",
}
