//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: api/protonotify/notify.proto

package protonotify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Notifier_OpenNotificationStream_FullMethodName = "/protonotify.Notifier/OpenNotificationStream"
)

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierClient interface {
	OpenNotificationStream(ctx context.Context, opts ...grpc.CallOption) (Notifier_OpenNotificationStreamClient, error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) OpenNotificationStream(ctx context.Context, opts ...grpc.CallOption) (Notifier_OpenNotificationStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Notifier_ServiceDesc.Streams[0], Notifier_OpenNotificationStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notifierOpenNotificationStreamClient{stream}
	return x, nil
}

type Notifier_OpenNotificationStreamClient interface {
	Send(*NotificationRequest) error
	Recv() (*NotificationResponse, error)
	grpc.ClientStream
}

type notifierOpenNotificationStreamClient struct {
	grpc.ClientStream
}

func (x *notifierOpenNotificationStreamClient) Send(m *NotificationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notifierOpenNotificationStreamClient) Recv() (*NotificationResponse, error) {
	m := new(NotificationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility
type NotifierServer interface {
	OpenNotificationStream(Notifier_OpenNotificationStreamServer) error
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServer struct {
}

func (UnimplementedNotifierServer) OpenNotificationStream(Notifier_OpenNotificationStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenNotificationStream not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s grpc.ServiceRegistrar, srv NotifierServer) {
	s.RegisterService(&Notifier_ServiceDesc, srv)
}

func _Notifier_OpenNotificationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotifierServer).OpenNotificationStream(&notifierOpenNotificationStreamServer{stream})
}

type Notifier_OpenNotificationStreamServer interface {
	Send(*NotificationResponse) error
	Recv() (*NotificationRequest, error)
	grpc.ServerStream
}

type notifierOpenNotificationStreamServer struct {
	grpc.ServerStream
}

func (x *notifierOpenNotificationStreamServer) Send(m *NotificationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notifierOpenNotificationStreamServer) Recv() (*NotificationRequest, error) {
	m := new(NotificationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Notifier_ServiceDesc is the grpc.ServiceDesc for Notifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protonotify.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenNotificationStream",
			Handler:       _Notifier_OpenNotificationStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/protonotify/notify.proto",
}
