{
 "title": "Demo",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sig_verifier_instance",
    "label": "Sig Verifier Servers",
    "query": {
     "query": "sc_component_type{component=\"sigverifier\"}"
    }
   },
   {
    "name": "coordinator_instance",
    "label": "Coordinator Servers",
    "query": {
     "query": "sc_component_type{component=\"coordinator\"}"
    }
   },
   {
    "name": "shards_service_instance",
    "label": "Shard Servers",
    "query": {
     "query": "sc_component_type{component=\"shards-service\"}"
    }
   },
   {
    "name": "generator_instance",
    "label": "Generator Servers",
    "query": {
     "query": "sc_component_type{component=\"generator\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total TXs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sc_e2e_requests", "legendFormat": "Sent" },
    { "expr": "sc_e2e_responses", "legendFormat": "Received ({{status}})" }
   ]
  },
  { "title": "Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "TX Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sc_e2e_responses[$__rate_interval])",
     "legendFormat": "Incoming responses"
    },
    {
     "expr": "rate(sc_e2e_requests[$__rate_interval])",
     "legendFormat": "Outgoing requests"
    }
   ]
  },
  {
   "title": "99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sc_generator_latency_bucket[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$generator_instance:.+\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$generator_instance:.+\"}",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$generator_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$generator_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$generator_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$generator_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$generator_instance:.+\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$generator_instance:.+\"}[$__rate_interval]))*8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$generator_instance:.+\"}[$__rate_interval]))*8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$generator_instance:.+\"} [$__rate_interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  { "title": "Shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total Throughput (RPS*)",
   "type": "timeseries",
   "description": "If the TX consists of multiple SNs (e.g. 4), it will be most probably split into different shards (e.g. 2 shards will get each 1 SN and 1 shard will get 2). It will count as one TX for each shard and that will give a false total of 3 TXs instead of 1.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(sc_component_throughput{direction=\"in\",instance=~\"$shards_service_instance:.+\"}[$__rate_interval]))",
     "legendFormat": "In ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(sc_component_throughput{direction=\"out\",instance=~\"$shards_service_instance:.+\"}[$__rate_interval])) * (-1)",
     "legendFormat": "Out ({{instance}})"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$shards_service_instance:.+\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$shards_service_instance:.+\"}",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$shards_service_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$shards_service_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$shards_service_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$shards_service_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$shards_service_instance:.+\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$shards_service_instance:.+\"}[$__rate_interval]))*8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$shards_service_instance:.+\"}[$__rate_interval]))*8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$shards_service_instance:.+\"} [$__rate_interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Channel-Buffer Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sc_channel_length{component=\"shards-service\"}",
     "legendFormat": "{{sub_component}} > {{channel}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sc_go_routines{component=\"shards-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Shard DB read/write 99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(sc_shard_db_read_latency_bucket[$__rate_interval]))",
     "legendFormat": "{{instance}} - Read"
    },
    {
     "expr": "histogram_quantile(0.95, rate(sc_shard_db_write_latency_bucket[$__rate_interval])) * -1",
     "legendFormat": "{{instance}} - Write"
    }
   ]
  },
  {
   "title": "Shard sizes (committed Serial numbers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sc_component_throughput{component=\"shards-service\", direction=\"out\"}",
     "legendFormat": "Shard {{sub_component}}"
    }
   ]
  },
  {
   "title": "Data structure sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sc_data_structure_size{component=\"shards-service\"}",
     "legendFormat": "{{sub_component}} > {{prop}}"
    }
   ]
  },
  {
   "title": "Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total throughput (TPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(sc_component_throughput{direction=\"in\",instance=~\"$coordinator_instance:.+\",sub_component=\"coordinator\"}[$__rate_interval]))",
       "legendFormat": "In ({{instance}})"
      },
      {
       "expr": "sum by (instance) (rate(sc_component_throughput{direction=\"out\",instance=~\"$coordinator_instance:.+\",sub_component=\"coordinator\"}[$__rate_interval])) * (-1)",
       "legendFormat": "Out ({{instance}})"
      }
     ]
    },
    {
     "title": "CPU Basic (System & User)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$coordinator_instance:.+\"}[$__rate_interval])))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$coordinator_instance:.+\"}",
       "legendFormat": "RAM Total ({{instance}})"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$coordinator_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$coordinator_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$coordinator_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$coordinator_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$coordinator_instance:.+\"})",
       "legendFormat": "RAM Used ({{instance}})"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$coordinator_instance:.+\"}[$__rate_interval]))*8",
       "legendFormat": "recv {{device}} ({{instance}})"
      },
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$coordinator_instance:.+\"}[$__rate_interval]))*8",
       "legendFormat": "trans {{device}}  ({{instance}})"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$coordinator_instance:.+\"} [$__rate_interval])",
       "legendFormat": "{{device}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Channel-Buffer Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "sc_channel_length{component=\"coordinator\"}",
       "legendFormat": "{{sub_component}} > {{channel}}"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "sc_go_routines{component=\"coordinator\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Detailed Throughput (TPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(sc_component_throughput{component=\"coordinator\", direction=\"in\"}[30s])",
       "legendFormat": "{{sub_component}} IN"
      },
      {
       "expr": "rate(sc_component_throughput{component=\"coordinator\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{sub_component}} OUT"
      }
     ]
    },
    {
     "title": "Dependency Graph Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sc_dependency_graph_pending_sns",
       "legendFormat": "Serial numbers"
      },
      {
       "expr": "sc_dependency_graph_pending_txs",
       "legendFormat": "TXs"
      }
     ]
    }
   ]
  },
  {
   "title": "Sig Verifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Throughput (TPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(sc_component_throughput{instance=~\"$sig_verifier_instance:.+\",sub_component=\"verifier_server\",direction=\"in\"}[$__rate_interval]))",
       "legendFormat": "In ({{instance}})"
      },
      {
       "expr": "sum by (instance) (-1 * rate(sc_component_throughput{instance=~\"$sig_verifier_instance:.+\",sub_component=\"verifier_server\",direction=\"out\"}[$__rate_interval]))",
       "legendFormat": "Out ({{instance}})"
      }
     ]
    },
    {
     "title": "Active Streams",
     "type": "gauge",
     "description": "How many clients have an open stream to the server",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sc_active_streams", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "99%-Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(sc_sigverifier_latency_bucket[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Basic (System & User)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$sig_verifier_instance:.+\"}[$__rate_interval])))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$sig_verifier_instance:.+\"}",
       "legendFormat": "RAM Total ({{instance}})"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$sig_verifier_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$sig_verifier_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$sig_verifier_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$sig_verifier_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$sig_verifier_instance:.+\"})",
       "legendFormat": "RAM Used ({{instance}})"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$sig_verifier_instance:.+\"}[$__rate_interval]))*8",
       "legendFormat": "recv {{device}} ({{instance}})"
      },
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$sig_verifier_instance:.+\"}[$__rate_interval]))*8",
       "legendFormat": "trans {{device}}  ({{instance}})"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$sig_verifier_instance:.+\"} [$__rate_interval])",
       "legendFormat": "{{device}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Channel-Buffer Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "sc_channel_length{component=\"sigverifier\"}",
       "legendFormat": "{{sub_component}} > {{channel}}"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "sc_go_routines{component=\"sigverifier\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Detailed Throughput (TPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"in\"}[$__rate_interval])",
       "legendFormat": "In {{sub_component}} ({{instance}})"
      },
      {
       "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "Out {{sub_component}} ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}