{
 "title": "Prometheus 2.0 Stats",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Cores Used",
   "type": "timeseries",
   "description": "The total CPU seconds spent on this procedure per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[30s])",
     "legendFormat": "{{instance}} > {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[30s]) * -1",
     "legendFormat": "{{instance}} > {{device}}"
    }
   ]
  },
  {
   "title": "Shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming / Outgoing TXs / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(sc_component_throughput{component=\"shards-service\", direction=\"in\"}[30s])",
       "legendFormat": "{{sub_component}} IN"
      },
      {
       "expr": "rate(sc_component_throughput{component=\"shards-service\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{sub_component}} OUT"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sc_net_io{component=\"shards-service\", direction=\"in\"}[30s])",
       "legendFormat": "{{name}} IN"
      },
      {
       "expr": "rate(sc_net_io{component=\"shards-service\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{name}} OUT"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sc_disk_io{component=\"shards-service\", direction=\"in\"}[30s])",
       "legendFormat": "{{name}} IN"
      },
      {
       "expr": "rate(sc_disk_io{component=\"shards-service\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{name}} OUT"
      }
     ]
    },
    {
     "title": "I/O Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[30s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total[30s]) * -1",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(node_disk_writes_completed_total[30s])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Channel-Buffer Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sc_channel_length{component=\"shards-service\"}",
       "legendFormat": "{{sub_component}} > {{channel}}"
      }
     ]
    },
    {
     "title": "Phase-2 Commit Duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      { "expr": "sc_shard_commit_duration", "legendFormat": "Shard {{sub_component}}" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(ne_process_cpu_seconds_total{component=\"shards-service\"}[30s])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(ne_go_gc_heap_allocs_bytes_total{component=\"shards-service\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming / Outgoing TXs / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(sc_component_throughput{component=\"coordinator\", direction=\"in\"}[30s])",
       "legendFormat": "{{sub_component}} IN"
      },
      {
       "expr": "rate(sc_component_throughput{component=\"coordinator\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{sub_component}} OUT"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sc_net_io{component=\"coordinator\", direction=\"in\"}[30s])",
       "legendFormat": "{{name}} IN"
      },
      {
       "expr": "rate(sc_net_io{component=\"coordinator\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{name}} OUT"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sc_disk_io{component=\"coordinator\", direction=\"in\"}[30s])",
       "legendFormat": "{{name}} IN"
      },
      {
       "expr": "rate(sc_disk_io{component=\"coordinator\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{name}} OUT"
      }
     ]
    },
    {
     "title": "Channel-Buffer Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sc_channel_length{component=\"coordinator\"}",
       "legendFormat": "{{sub_component}} > {{channel}}"
      }
     ]
    },
    {
     "title": "Dependency Graph Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sc_dependency_graph_pending_sns",
       "legendFormat": "Serial numbers"
      },
      {
       "expr": "sc_dependency_graph_pending_txs",
       "legendFormat": "TXs"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(ne_process_cpu_seconds_total{component=\"coordinator\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(ne_go_gc_heap_allocs_bytes_total{component=\"coordinator\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sig Verifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming / Outgoing TXs / sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"in\"}[30s])",
       "legendFormat": "{{sub_component}} IN"
      },
      {
       "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{sub_component}} OUT"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sc_net_io{component=\"sigverifier\", direction=\"in\"}[30s])",
       "legendFormat": "{{name}} IN"
      },
      {
       "expr": "rate(sc_net_io{component=\"sigverifier\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{name}} OUT"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(sc_disk_io{component=\"sigverifier\", direction=\"in\"}[30s])",
       "legendFormat": "{{name}} IN"
      },
      {
       "expr": "rate(sc_disk_io{component=\"sigverifier\", direction=\"out\"}[30s]) * -1",
       "legendFormat": "{{name}} OUT"
      }
     ]
    },
    {
     "title": "Channel-Buffer Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sc_channel_length{component=\"sigverifier\"}",
       "legendFormat": "{{sub_component}} > {{channel}}"
      }
     ]
    },
    {
     "title": "Active Streams",
     "type": "gauge",
     "description": "How many clients have an open stream to the server",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sc_active_streams", "legendFormat": "blocks" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(ne_process_cpu_seconds_total{component=\"sigverifier\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(ne_go_gc_heap_allocs_bytes_total{component=\"sigverifier\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}