// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: api/protocoordinatorservice/coordinator.proto

package protocoordinatorservice

import (
	context "context"
	protoblocktx "github.ibm.com/decentralized-trust-research/scalable-committer/api/protoblocktx"
	protosigverifierservice "github.ibm.com/decentralized-trust-research/scalable-committer/api/protosigverifierservice"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Coordinator_SetMetaNamespaceVerificationKey_FullMethodName = "/protocoordinatorservice.Coordinator/SetMetaNamespaceVerificationKey"
	Coordinator_BlockProcessing_FullMethodName                 = "/protocoordinatorservice.Coordinator/BlockProcessing"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorClient interface {
	SetMetaNamespaceVerificationKey(ctx context.Context, in *protosigverifierservice.Key, opts ...grpc.CallOption) (*Empty, error)
	BlockProcessing(ctx context.Context, opts ...grpc.CallOption) (Coordinator_BlockProcessingClient, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) SetMetaNamespaceVerificationKey(ctx context.Context, in *protosigverifierservice.Key, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Coordinator_SetMetaNamespaceVerificationKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) BlockProcessing(ctx context.Context, opts ...grpc.CallOption) (Coordinator_BlockProcessingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Coordinator_ServiceDesc.Streams[0], Coordinator_BlockProcessing_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &coordinatorBlockProcessingClient{stream}
	return x, nil
}

type Coordinator_BlockProcessingClient interface {
	Send(*protoblocktx.Block) error
	Recv() (*TxValidationStatusBatch, error)
	grpc.ClientStream
}

type coordinatorBlockProcessingClient struct {
	grpc.ClientStream
}

func (x *coordinatorBlockProcessingClient) Send(m *protoblocktx.Block) error {
	return x.ClientStream.SendMsg(m)
}

func (x *coordinatorBlockProcessingClient) Recv() (*TxValidationStatusBatch, error) {
	m := new(TxValidationStatusBatch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility
type CoordinatorServer interface {
	SetMetaNamespaceVerificationKey(context.Context, *protosigverifierservice.Key) (*Empty, error)
	BlockProcessing(Coordinator_BlockProcessingServer) error
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (UnimplementedCoordinatorServer) SetMetaNamespaceVerificationKey(context.Context, *protosigverifierservice.Key) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMetaNamespaceVerificationKey not implemented")
}
func (UnimplementedCoordinatorServer) BlockProcessing(Coordinator_BlockProcessingServer) error {
	return status.Errorf(codes.Unimplemented, "method BlockProcessing not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_SetMetaNamespaceVerificationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protosigverifierservice.Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).SetMetaNamespaceVerificationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_SetMetaNamespaceVerificationKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).SetMetaNamespaceVerificationKey(ctx, req.(*protosigverifierservice.Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_BlockProcessing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServer).BlockProcessing(&coordinatorBlockProcessingServer{stream})
}

type Coordinator_BlockProcessingServer interface {
	Send(*TxValidationStatusBatch) error
	Recv() (*protoblocktx.Block, error)
	grpc.ServerStream
}

type coordinatorBlockProcessingServer struct {
	grpc.ServerStream
}

func (x *coordinatorBlockProcessingServer) Send(m *TxValidationStatusBatch) error {
	return x.ServerStream.SendMsg(m)
}

func (x *coordinatorBlockProcessingServer) Recv() (*protoblocktx.Block, error) {
	m := new(protoblocktx.Block)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocoordinatorservice.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMetaNamespaceVerificationKey",
			Handler:    _Coordinator_SetMetaNamespaceVerificationKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BlockProcessing",
			Handler:       _Coordinator_BlockProcessing_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/protocoordinatorservice/coordinator.proto",
}
