/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package workload

// Generator generates new T each time Next() is called.
type Generator[T any] interface {
	Next() T
}

// MultiGenerator generates an array of Count items, with items generated by Gen.
type MultiGenerator[T any] struct {
	Count int
	Gen   Generator[T]
}

// Next yields an array of items.
func (g *MultiGenerator[T]) Next() []T {
	return GenerateArray(g.Gen, g.Count)
}

// GenerateArray generates an array of items of the requested size given a generator.
func GenerateArray[G Generator[T], T any](g G, size int) []T {
	arr := make([]T, size)
	for i := range arr {
		arr[i] = g.Next()
	}
	return arr
}
